<!DOCTYPE html><html><head><title>HGMD Mutation Result</title><link rel='stylesheet' type='text/css' href='css/global.css'><META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'></head><body>

<div class='sidemenu' id='opac'>
<div class='sidelink'><span class='a'>
<a class='sidebar' href='search_gene.php'>G</a><br>
<a class='sidebar' href='search_mut.php'>M</a><br>
<a class='sidebar' href='search_ref.php'>R</a><br>
<a class='sidebar' href='search_batch.php'>B</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>A</a><br><hr>
<a class='sidebar' href='stats.php'>S</a><br>
<a class='sidebar' href='info.php'>I</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>S</a><br>
<hr>
<a class='sidebar' href='start.php'>H</a><br>
</span><span class='b'>
<a class='sidebar' href='search_gene.php'>Gene</a><br>
<a class='sidebar' href='search_mut.php'>Mutation</a><br>
<a class='sidebar' href='search_ref.php'>Reference</a><br>
<a class='sidebar' href='search_batch.php'>Batch</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a><br><hr>
<a class='sidebar' href='stats.php'>Statistics</a><br>
<a class='sidebar' href='info.php'>Information</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a><br>
<hr>
<a class='sidebar' href='start.php'>Home</a><br>
</span>
</div>
</div><div class='top'><div class='logo1'><a href='http://www.hgmd.cf.ac.uk/' target='HGMDmain'><img id='hgmdlogo' src='bar/hgmd_new2.png' alt='HGMD'></a></div><div class='title'>HGMD&reg; Professional 2013.4 - 15<sup>th</sup> December 2013</div><div class='logo2'><a href='http://www.biobase-international.com' target='Biobase'><img src='bar/biobase_logo.png' alt='BioBase'></a></div><div class='links'> <a class='sidebar' href='search_gene.php'>Gene</a>
<a class='sidebar' href='search_mut.php'>Mutation</a>
<a class='sidebar' href='search_ref.php'>Reference</a>
<a class='sidebar' href='search_batch.php'>Batch</a> <a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a> | <a class='sidebar' href='stats.php'>Statistics</a>
<a class='sidebar' href='info.php'>Information</a>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a> |
<a class='sidebar' href='start.php'>Home</a></div></div><div class='content'><a name='top'></a><h3 class='heading'>All 79 mutations in <a href='gene.php?gene=DES'>DES</a></h3><table><tr class='odd'><td class='center'><a class='black' href='#miss/nons'>missense/nonsense</a></td><td class='center'><a class='black' href='#splice'>splicing</a></td><td class='center'><a class='black' href='#dels'>small deletions</a></td><td class='center'><a class='black' href='#ins'>small insertions</a></td><td class='center'><a class='black' href='#indels'>small indels</a></td><td class='center'><a class='black' href='#grdel'>gross deletions</a></td></tr></table><a name='miss/nons'></a><h3 class='heading'>Missense/nonsense : 59 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th><a href='useful.php#cods'>HGMD</a> codon<br>change</th><th><a href='useful.php#cods'>HGMD</a> amino<br>acid change</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(protein)</span></th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044223'><input type='submit' value='CM044223'></form></td>
	<td>AGC-ATC</td><td>Ser2Ile</td><td>c.5G>T</td><td>p.S2I</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14711882&amp;dopt=Abstract' target=ref>Selcen (2004) Brain <b>127,</b> 439</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19763525&amp;dopt=Abstract' target=ref>Sharma (2009) <i>J Mol Med</i> <b>87:</b> 1207</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283189'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs58999456' target='dbSNP' title='Link to rs58999456'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1110330'><input type='submit' value='CM1110330'></form></td>
	<td>TCC-TTC</td><td>Ser7Phe</td><td>c.20C>T</td><td>p.S7F</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22106715&amp;dopt=Abstract' target=ref>Vattemi (2011) Acta Myol <b>30,</b> 121</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283204'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM105026'><input type='submit' value='CM105026'></form></td>
	<td>TCC-TTC</td><td>Ser12Phe</td><td>c.35C>T</td><td>p.S12F</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20696008&amp;dopt=Abstract' target=ref>Hong (2010) Neuropathol Appl Neurobiol <b>37,</b> 257</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20654101&amp;dopt=Abstract' target=ref>Hong (2010) <i>Zhonghua Xin Xue Guan Bing Za Zhi</i> <b>38:</b> 420</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283219'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607495' target='dbSNP' title='Link to rs267607495'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM074140'><input type='submit' value='CM074140'></form></td>
	<td>TCC-TTC</td><td>Ser13Phe</td><td>c.38C>T</td><td>p.S13F</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17720647&amp;dopt=Abstract' target=ref>Bergman (2007) Eur J Med Genet <b>50,</b> 355</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19763525&amp;dopt=Abstract' target=ref>Sharma (2009) <i>J Mol Med</i> <b>87:</b> 1207</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19879535&amp;dopt=Abstract' target=ref>van Tintelen (2009) <i>Heart Rhythm</i> <b>6:</b> 1574</a> [Additional report]</span><br><span class='td'>3 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283222'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62636495' target='dbSNP' title='Link to rs62636495'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM066560'><input type='submit' value='CM066560'></form></td>
	<td>cCGC-TGC</td><td>Arg16Cys</td><td>c.46C>T</td><td>p.R16C</td><td>Cardiomyopathy, restrictive with atrioventricular block</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16376610&amp;dopt=Abstract' target=ref>Arbustini (2006) Eur J Heart Fail <b>8,</b> 477</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19763525&amp;dopt=Abstract' target=ref>Sharma (2009) <i>J Mol Med</i> <b>87:</b> 1207</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283230'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs60798368' target='dbSNP' title='Link to rs60798368'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044224'><input type='submit' value='CM044224'></form></td>
	<td>TCC-TTC</td><td>Ser46Phe</td><td>c.137C>T</td><td>p.S46F</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14711882&amp;dopt=Abstract' target=ref>Selcen (2004) Brain <b>127,</b> 439</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19763525&amp;dopt=Abstract' target=ref>Sharma (2009) <i>J Mol Med</i> <b>87:</b> 1207</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283321'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs60794845' target='dbSNP' title='Link to rs60794845'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044225'><input type='submit' value='CM044225'></form></td>
	<td>TCC-TAC</td><td>Ser46Tyr</td><td>c.137C>A</td><td>p.S46Y</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14711882&amp;dopt=Abstract' target=ref>Selcen (2004) Brain <b>127,</b> 439</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19763525&amp;dopt=Abstract' target=ref>Sharma (2009) <i>J Mol Med</i> <b>87:</b> 1207</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283321'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs60794845' target='dbSNP' title='Link to rs60794845'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM070888'><input type='submit' value='CM070888'></form></td>
	<td>cGAG-AAG</td><td>Glu108Lys</td><td>c.322G>A</td><td>p.E108K</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17325244&amp;dopt=Abstract' target=ref>Taylor (2007) Circulation <b>115,</b> 1244</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283506'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62636490' target='dbSNP' title='Link to rs62636490'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136433'><input type='submit' value='CM136433'></form></td>
	<td>cGAG-TAG</td><td>Glu108Term</td><td>c.322G>T</td><td>p.E108*</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23575897&amp;dopt=Abstract' target=ref>Henderson (2013) Acta Neuropathol <b>125,</b> 917</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283506'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM107449'><input type='submit' value='CM107449'></form></td>
	<td>AAT-AGT</td><td>Asn116Ser</td><td>c.347A>G</td><td>p.N116S</td><td>Arrhythmogenic right ventricular cardiomyopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20829228&amp;dopt=Abstract' target=ref>Klauke (2010) Hum Mol Genet <b>19,</b> 4595</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22403400&amp;dopt=Abstract' target=ref>Brodehl (2012) <i>J Biol Chem</i> <b>287:</b> 16047</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283531'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607499' target='dbSNP' title='Link to rs267607499'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM121992'><input type='submit' value='CM121992'></form></td>
	<td>cAAG-TAG</td><td>Lys144Term</td><td>c.430A>T</td><td>p.K144*</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22153487&amp;dopt=Abstract' target=ref>Wahbi (2012) Neuromuscul Disord <b>22,</b> 211</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283614'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117560'><input type='submit' value='CM117560'></form></td>
	<td>GCG-GTG</td><td>Ala213Val</td><td>c.638C>T</td><td>p.A213V</td><td>Heart dilation, association with</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21842594&amp;dopt=Abstract' target=ref>Kostareva (2011) Acta Myol <b>30,</b> 42</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23168288&amp;dopt=Abstract' target=ref>Lorenzon (2012) <i>Am J Cardiol</i> <b>:</b> </a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='fp' title='Disease-associated polymorphism'>DP</span>  <span class='gen' title='Chr2:220284876'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs41272699' target='dbSNP' title='Link to rs41272699'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.008 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044876'><input type='submit' value='CM044876'></form></td>
	<td>GAC-GTC</td><td>Asp214Val</td><td>c.641A>T</td><td>p.D214V</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14724127&amp;dopt=Abstract' target=ref>Goldfarb (2004) Brain <b>127,</b> 723</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220284974'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1211120'><input type='submit' value='CM1211120'></form></td>
	<td>gAAA-GAA</td><td>Lys241Glu</td><td>c.721A>G</td><td>p.K241E</td><td>Phenotype modifier</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23168288&amp;dopt=Abstract' target=ref>Lorenzon (2013) Am J Cardiol <b>111,</b> 400</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr2:220285054'>GEN</span> <span class='cpg' title='patient also carries PKP2 p.T816RfsX10.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs201945924' target='dbSNP' title='Link to rs201945924'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM121996'><input type='submit' value='CM121996'></form></td>
	<td>GAGg-GAT</td><td>Glu245Asp</td><td>c.735G>T</td><td>p.E245D</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22153487&amp;dopt=Abstract' target=ref>Wahbi (2012) Neuromuscul Disord <b>22,</b> 211</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285068'>GEN</span> <span class='cpg' title='Last nucleotide of ex. 3, may affect splicing'>COM</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044877'><input type='submit' value='CM044877'></form></td>
	<td>GAGa-GAC</td><td>Glu246Asp</td><td>c.738G>C</td><td>p.E246D</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14724127&amp;dopt=Abstract' target=ref>Goldfarb (2004) Brain <b>127,</b> 723</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16449718&amp;dopt=Abstract' target=ref>Hager (2006) <i>Circulation</i> <b>113:</b> e53</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19005210&amp;dopt=Abstract' target=ref>Conover (2009) <i>Mol Biol Cell</i> <b>20:</b> 834</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285219'>GEN</span> <span class='cpg' title='Descr. as Glu245Asp in Table 1. Subst. conf. by PC <183>. new numbering based on NM_001927.3'>COM</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM105028'><input type='submit' value='CM105028'></form></td>
	<td>CTC-CGC</td><td>Leu274Arg</td><td>c.821T>G</td><td>p.L274R</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20696008&amp;dopt=Abstract' target=ref>Hong (2010) Neuropathol Appl Neurobiol <b>37,</b> 257</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20654101&amp;dopt=Abstract' target=ref>Hong (2010) <i>Zhonghua Xin Xue Guan Bing Za Zhi</i> <b>38:</b> 420</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285302'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM105027'><input type='submit' value='CM105027'></form></td>
	<td>CTC-CCC</td><td>Leu274Pro</td><td>c.821T>C</td><td>p.L274P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20696008&amp;dopt=Abstract' target=ref>Hong (2010) Neuropathol Appl Neurobiol <b>37,</b> 257</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20654101&amp;dopt=Abstract' target=ref>Hong (2010) <i>Zhonghua Xin Xue Guan Bing Za Zhi</i> <b>38:</b> 420</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285302'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1310426'><input type='submit' value='CM1310426'></form></td>
	<td>GCG-GTG</td><td>Ala285Val</td><td>c.854C>T</td><td>p.A285V</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23300193&amp;dopt=Abstract' target=ref>Tse (2013) Hum Mol Genet <b>22,</b> 1395</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285335'>GEN</span> <span class='cpg' title='Descr. as c940C>T A285V, seq. in Fig. 1.'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM070891'><input type='submit' value='CM070891'></form></td>
	<td>TCG-TTG</td><td>Ser298Leu</td><td>c.893C>T</td><td>p.S298L</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17325244&amp;dopt=Abstract' target=ref>Taylor (2007) Circulation <b>115,</b> 1244</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23299917&amp;dopt=Abstract' target=ref>Andreasen (2013) <i>Eur J Hum Genet</i> <b>21:</b> 918</a> [Additional report]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23861362&amp;dopt=Abstract' target=ref>Ng (2013) <i>Circ Cardiovasc Genet</i> <b>6:</b> 337</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285374'>GEN</span> <span class='cpg' title='c.979C>T based on NM_001927.3'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62636491' target='dbSNP' title='Link to rs62636491'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137784'><input type='submit' value='CM137784'></form></td>
	<td>GAC-GCC</td><td>Asp312Ala</td><td>c.935A>C</td><td>p.D312A</td><td>Cardiomyopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23785128&amp;dopt=Abstract' target=ref>Mook (2013) J Med Genet <b>50,</b> 614</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr2:220285587'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM070887'><input type='submit' value='CM070887'></form></td>
	<td>cGAC-AAC</td><td>Asp312Asn</td><td>c.934G>A</td><td>p.D312N</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17325244&amp;dopt=Abstract' target=ref>Taylor (2007) Circulation <b>115,</b> 1244</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23299917&amp;dopt=Abstract' target=ref>Andreasen (2013) <i>Eur J Hum Genet</i> <b>21:</b> 918</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285586'>GEN</span> <span class='cpg' title='c.1020G>A based on NM_001927.3'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs34337334' target='dbSNP' title='Link to rs34337334'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM121993'><input type='submit' value='CM121993'></form></td>
	<td>tGAC-TAC</td><td>Asp336Tyr</td><td>c.1006G>T</td><td>p.D336Y</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22153487&amp;dopt=Abstract' target=ref>Wahbi (2012) Neuromuscul Disord <b>22,</b> 211</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285658'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980537'><input type='submit' value='CM980537'></form></td>
	<td>cGCC-CCC</td><td>Ala337Pro</td><td>c.1009G>C</td><td>p.A337P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9697706&amp;dopt=Abstract' target=ref>Goldfarb (1998) Nat Genet <b>19,</b> 402</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285661'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs59962885' target='dbSNP' title='Link to rs59962885'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM063949'><input type='submit' value='CM063949'></form></td>
	<td>CTG-CGG</td><td>Leu338Arg</td><td>c.1013T>G</td><td>p.L338R</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16865695&amp;dopt=Abstract' target=ref>Goudeau (2006) Hum Mutat <b>27,</b> 906</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285665'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs57496341' target='dbSNP' title='Link to rs57496341'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM000367'><input type='submit' value='CM000367'></form></td>
	<td>tAAC-GAC</td><td>Asn342Asp</td><td>c.1024A>G</td><td>p.N342D</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10717012&amp;dopt=Abstract' target=ref>Dalakas (2000) N Engl J Med <b>342,</b> 770</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12609507&amp;dopt=Abstract' target=ref>Dalakas (2003) <i>Neuromuscul Disord</i> <b>13:</b> 252</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22215463&amp;dopt=Abstract' target=ref>van Spaendonck-Zwarts (2012) <i>Neth Heart J</i> <b>20:</b> 219</a> [Additional phenotype]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286062'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607482' target='dbSNP' title='Link to rs267607482'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM992621'><input type='submit' value='CM992621'></form></td>
	<td>CTG-CCG</td><td>Leu345Pro</td><td>c.1034T>C</td><td>p.L345P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10545598&amp;dopt=Abstract' target=ref>Sjoberg (1999) Hum Mol Genet <b>8,</b> 2191</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286072'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs57639980' target='dbSNP' title='Link to rs57639980'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM051448'><input type='submit' value='CM051448'></form></td>
	<td>CGG-CCG</td><td>Arg350Pro</td><td>c.1049G>C</td><td>p.R350P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15800015&amp;dopt=Abstract' target=ref>Bar (2005) Hum Mol Genet <b>14,</b> 1251</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17439987&amp;dopt=Abstract' target=ref>Walter (2007) <i>Brain</i> <b>130:</b> 1485</a> [Additional report]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20448486&amp;dopt=Abstract' target=ref>Levin (2010) <i>J Neuropathol Exp Neurol</i> <b>69:</b> 415</a> [Functional characterisation]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286087'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs57965306' target='dbSNP' title='Link to rs57965306'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM070890'><input type='submit' value='CM070890'></form></td>
	<td>gCGG-TGG</td><td>Arg350Trp</td><td>c.1048C>T</td><td>p.R350W</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17325244&amp;dopt=Abstract' target=ref>Taylor (2007) Circulation <b>115,</b> 1244</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23299917&amp;dopt=Abstract' target=ref>Andreasen (2013) <i>Eur J Hum Genet</i> <b>21:</b> 918</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286086'>GEN</span> <span class='cpg' title='c.1134C>T, based on NM_001927.3.'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62636492' target='dbSNP' title='Link to rs62636492'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM052845'><input type='submit' value='CM052845'></form></td>
	<td>CGA-CCA</td><td>Arg355Pro</td><td>c.1064G>C</td><td>p.R355P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16009553&amp;dopt=Abstract' target=ref>Fidzianska (2005) Neuromuscul Disord <b>15,</b> 525</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286102'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs61368398' target='dbSNP' title='Link to rs61368398'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM032564'><input type='submit' value='CM032564'></form></td>
	<td>tGCC-CCC</td><td>Ala357Pro</td><td>c.1069G>C</td><td>p.A357P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12766977&amp;dopt=Abstract' target=ref>Dagvadorj (2003) Muscle Nerve <b>27,</b> 669</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286107'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs58898021' target='dbSNP' title='Link to rs58898021'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980538'><input type='submit' value='CM980538'></form></td>
	<td>gGCC-CCC</td><td>Ala360Pro</td><td>c.1078G>C</td><td>p.A360P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9697706&amp;dopt=Abstract' target=ref>Goldfarb (1998) Nat Genet <b>19,</b> 402</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286116'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121913000' target='dbSNP' title='Link to rs121913000'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM072981'><input type='submit' value='CM072981'></form></td>
	<td>cATT-TTT</td><td>Ile367Phe</td><td>c.1099A>T</td><td>p.I367F</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17418574&amp;dopt=Abstract' target=ref>Olive (2007) Neuromuscul Disord <b>17,</b> 443</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286137'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62636494' target='dbSNP' title='Link to rs62636494'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM032565'><input type='submit' value='CM032565'></form></td>
	<td>CTG-CCG</td><td>Leu370Pro</td><td>c.1109T>C</td><td>p.L370P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12766977&amp;dopt=Abstract' target=ref>Dagvadorj (2003) Muscle Nerve <b>27,</b> 669</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21676617&amp;dopt=Abstract' target=ref>Olivé (2011) <i>Neuromuscul Disord</i> <b>21:</b> 533</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286147'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs59308628' target='dbSNP' title='Link to rs59308628'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM082597'><input type='submit' value='CM082597'></form></td>
	<td>CTC-CCC</td><td>Leu377Pro</td><td>c.1130T>C</td><td>p.L377P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18504128&amp;dopt=Abstract' target=ref>Strach (2008) Neuromuscul Disord <b>18,</b> 475</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286168'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM003731'><input type='submit' value='CM003731'></form></td>
	<td>CTG-CCG</td><td>Leu385Pro</td><td>c.1154T>C</td><td>p.L385P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11061256&amp;dopt=Abstract' target=ref>Sugawara (2000) Neurology <b>55,</b> 986</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286192'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs57955682' target='dbSNP' title='Link to rs57955682'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM013258'><input type='submit' value='CM013258'></form></td>
	<td>CAG-CCG</td><td>Gln389Pro</td><td>c.1166A>C</td><td>p.Q389P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11668632&amp;dopt=Abstract' target=ref>Goudeau (2001) Hum Mutat <b>18,</b> 388</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286204'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121913004' target='dbSNP' title='Link to rs121913004'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM072983'><input type='submit' value='CM072983'></form></td>
	<td>CTC-CCC</td><td>Leu392Pro</td><td>c.1175T>C</td><td>p.L392P</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17418574&amp;dopt=Abstract' target=ref>Olive (2007) Neuromuscul Disord <b>17,</b> 443</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21676617&amp;dopt=Abstract' target=ref>Olivé (2011) <i>Neuromuscul Disord</i> <b>21:</b> 533</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286213'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62636493' target='dbSNP' title='Link to rs62636493'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980539'><input type='submit' value='CM980539'></form></td>
	<td>AAC-ATC</td><td>Asn393Ile</td><td>c.1178A>T</td><td>p.N393I</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9697706&amp;dopt=Abstract' target=ref>Goldfarb (1998) Nat Genet <b>19,</b> 402</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286216'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121913001' target='dbSNP' title='Link to rs121913001'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM063951'><input type='submit' value='CM063951'></form></td>
	<td>gGAT-TAT</td><td>Asp399Tyr</td><td>c.1195G>T</td><td>p.D399Y</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16865695&amp;dopt=Abstract' target=ref>Goudeau (2006) Hum Mutat <b>27,</b> 906</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286233'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs61130669' target='dbSNP' title='Link to rs61130669'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM063950'><input type='submit' value='CM063950'></form></td>
	<td>gGAG-AAG</td><td>Glu401Lys</td><td>c.1201G>A</td><td>p.E401K</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16865695&amp;dopt=Abstract' target=ref>Goudeau (2006) Hum Mutat <b>27,</b> 906</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286239'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs57694264' target='dbSNP' title='Link to rs57694264'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM000368'><input type='submit' value='CM000368'></form></td>
	<td>cCGG-TGG</td><td>Arg406Trp</td><td>c.1216C>T</td><td>p.R406W</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10717012&amp;dopt=Abstract' target=ref>Dalakas (2000) N Engl J Med <b>342,</b> 770</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286254'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121913003' target='dbSNP' title='Link to rs121913003'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM071702'><input type='submit' value='CM071702'></form></td>
	<td>gGAG-AAG</td><td>Glu413Lys</td><td>c.1237G>A</td><td>p.E413K</td><td>Cardiomyopathy, restrictive with atrioventricular block</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16890305&amp;dopt=Abstract' target=ref>Pruszczyk (2007) Int J Cardiol <b>117,</b> 244</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20448486&amp;dopt=Abstract' target=ref>Levin (2010) <i>J Neuropathol Exp Neurol</i> <b>69:</b> 415</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286275'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs61726467' target='dbSNP' title='Link to rs61726467'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM088474'><input type='submit' value='CM088474'></form></td>
	<td>cCGG-TGG</td><td>Arg415Trp</td><td>c.1243C>T</td><td>p.R415W</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19181099&amp;dopt=Abstract' target=ref>Goldfarb (2008) Adv Exp Med Biol <b>642,</b> 131</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286281'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM072982'><input type='submit' value='CM072982'></form></td>
	<td>cCCC-TCC</td><td>Pro419Ser</td><td>c.1255C>T</td><td>p.P419S</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17418574&amp;dopt=Abstract' target=ref>Olive (2007) Neuromuscul Disord <b>17,</b> 443</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21676617&amp;dopt=Abstract' target=ref>Olivé (2011) <i>Neuromuscul Disord</i> <b>21:</b> 533</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22395865&amp;dopt=Abstract' target=ref>Hedberg (2012) <i>Eur J Hum Genet</i> <b>20:</b> 984</a> [Additional phenotype]</span><br><span class='td'>2 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220288509'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs62635763' target='dbSNP' title='Link to rs62635763'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136373'><input type='submit' value='CM136373'></form></td>
	<td>cCGA-TGA</td><td>Arg429Term</td><td>c.1285C>T</td><td>p.R429*</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23815709&amp;dopt=Abstract' target=ref>McLaughlin (2013) BMC Med Genet <b>14,</b> </a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220288539'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM121994'><input type='submit' value='CM121994'></form></td>
	<td>tGAG-AAG</td><td>Glu439Lys</td><td>c.1315G>A</td><td>p.E439K</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22153487&amp;dopt=Abstract' target=ref>Wahbi (2012) Neuromuscul Disord <b>22,</b> 211</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290411'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM071699'><input type='submit' value='CM071699'></form></td>
	<td>ACC-ATC</td><td>Thr442Ile</td><td>c.1325C>T</td><td>p.T442I</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17221859&amp;dopt=Abstract' target=ref>Bar (2007) Hum Mutat <b>28,</b> 374</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290421'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121913005' target='dbSNP' title='Link to rs121913005'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM105099'><input type='submit' value='CM105099'></form></td>
	<td>gACG-GCG</td><td>Thr445Ala</td><td>c.1333A>G</td><td>p.T445A</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20696008&amp;dopt=Abstract' target=ref>Hong (2010) Neuropathol Appl Neurobiol <b>37,</b> 257</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290429'>GEN</span> <span class='cpg' title='Descr. as c.1333A>G T445F, mut. conf. by PC <1052>.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607498' target='dbSNP' title='Link to rs267607498'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044875'><input type='submit' value='CM044875'></form></td>
	<td>AAG-ATG</td><td>Lys449Met</td><td>c.1346A>T</td><td>p.K449M</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15495235&amp;dopt=Abstract' target=ref>Paulin (2004) J Pathol <b>204,</b> 418</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290442'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM044226'><input type='submit' value='CM044226'></form></td>
	<td>AAG-ACG</td><td>Lys449Thr</td><td>c.1346A>C</td><td>p.K449T</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14711882&amp;dopt=Abstract' target=ref>Selcen (2004) Brain <b>127,</b> 439</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23051780&amp;dopt=Abstract' target=ref>Maddison (2012) <i>Eur Neurol</i> <b>68:</b> 279</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290442'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607485' target='dbSNP' title='Link to rs267607485'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM000369'><input type='submit' value='CM000369'></form></td>
	<td>ATCg-ATG</td><td>Ile451Met</td><td>c.1353C>G</td><td>p.I451M</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10430757&amp;dopt=Abstract' target=ref>Li (1999) Circulation <b>100,</b> 461</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12609507&amp;dopt=Abstract' target=ref>Dalakas (2003) <i>Neuromuscul Disord</i> <b>13:</b> 252</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290449'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121913002' target='dbSNP' title='Link to rs121913002'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM066559'><input type='submit' value='CM066559'></form></td>
	<td>ACA-ATA</td><td>Thr453Ile</td><td>c.1358C>T</td><td>p.T453I</td><td>Cardiomyopathy, restrictive with atrioventricular block</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16376610&amp;dopt=Abstract' target=ref>Arbustini (2006) Eur J Heart Fail <b>8,</b> 477</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290454'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607488' target='dbSNP' title='Link to rs267607488'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM071700'><input type='submit' value='CM071700'></form></td>
	<td>aCGG-TGG</td><td>Arg454Trp</td><td>c.1360C>T</td><td>p.R454W</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17221859&amp;dopt=Abstract' target=ref>Bar (2007) Hum Mutat <b>28,</b> 374</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20448486&amp;dopt=Abstract' target=ref>Levin (2010) <i>J Neuropathol Exp Neurol</i> <b>69:</b> 415</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22403400&amp;dopt=Abstract' target=ref>Brodehl (2012) <i>J Biol Chem</i> <b>287:</b> 16047</a> [Functional characterisation]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290456'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607490' target='dbSNP' title='Link to rs267607490'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM105029'><input type='submit' value='CM105029'></form></td>
	<td>GAG-GTG</td><td>Glu457Val</td><td>c.1370A>T</td><td>p.E457V</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20696008&amp;dopt=Abstract' target=ref>Hong (2010) Neuropathol Appl Neurobiol <b>37,</b> 257</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20654101&amp;dopt=Abstract' target=ref>Hong (2010) <i>Zhonghua Xin Xue Guan Bing Za Zhi</i> <b>38:</b> 420</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290466'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607496' target='dbSNP' title='Link to rs267607496'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM070889'><input type='submit' value='CM070889'></form></td>
	<td>cGTC-ATC</td><td>Val459Ile</td><td>c.1375G>A</td><td>p.V459I</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17325244&amp;dopt=Abstract' target=ref>Taylor (2007) Circulation <b>115,</b> 1244</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20474083&amp;dopt=Abstract' target=ref>Zimmerman (2010) <i>Genet Med</i> <b>12:</b> 268</a> [Additional report]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20981092&amp;dopt=Abstract' target=ref>1000 Genomes Project (2010) <i>Nature</i> <b>467:</b> 1061</a> [Additional report]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290674'>GEN</span> <span class='cpg' title='c.1461G>A, based on NM_001927.3.'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs73991549' target='dbSNP' title='Link to rs73991549'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.006 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM071701'><input type='submit' value='CM071701'></form></td>
	<td>AGT-ATT</td><td>Ser460Ile</td><td>c.1379G>T</td><td>p.S460I</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17221859&amp;dopt=Abstract' target=ref>Bar (2007) Hum Mutat <b>28,</b> 374</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290678'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607491' target='dbSNP' title='Link to rs267607491'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM060952'><input type='submit' value='CM060952'></form></td>
	<td>aGTG-ATG</td><td>Val469Met</td><td>c.1405G>A</td><td>p.V469M</td><td>Cardiomyopathy, hypertrophic</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16585054&amp;dopt=Abstract' target=ref>Muntoni (2006) Brain <b>129,</b> 1260</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290704'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607487' target='dbSNP' title='Link to rs267607487'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM121991'><input type='submit' value='CM121991'></form></td>
	<td>TAAa-TAC</td><td>Term471Tyr</td><td>c.1413A>C</td><td>p.*471Y</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22153487&amp;dopt=Abstract' target=ref>Wahbi (2012) Neuromuscul Disord <b>22,</b> 211</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290712'>GEN</span>  </td></tr>

</table><a name='splice'></a><h3 class='heading'>Splicing : 7 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>HGMD splicing mutation</th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS094560'><input type='submit' value='CS094560'></form></td><td>IVS2 as A-C -2</td><td>c.640-2A>C</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19716701&amp;dopt=Abstract' target=ref>Dunand (2009) Neuromuscul Disord <b>19,</b> 570</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220284971'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS068099'><input type='submit' value='CS068099'></form></td><td>IVS2 as A-G -2</td><td>c.640-2A>G</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17626518&amp;dopt=Abstract' target=ref>Kostareva (2006) Acta Myol <b>25,</b> 109</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220284971'>GEN</span> <span class='cpg' title='causes skipping of exon 3.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607492' target='dbSNP' title='Link to rs267607492'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS044962'><input type='submit' value='CS044962'></form></td><td>IVS2 as A-T -2</td><td>c.640-2A>T</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14724127&amp;dopt=Abstract' target=ref>Goldfarb (2004) Brain <b>127,</b> 723</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220284971'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS003066'><input type='submit' value='CS003066'></form></td><td>IVS2 as G-A -1</td><td>c.640-1G>A</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11073539&amp;dopt=Abstract' target=ref>Park (2000) J Med Genet <b>37,</b> 851</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220284972'>GEN</span> <span class='cpg' title='causes deletion of exon 3 (delD214-E245).'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607484' target='dbSNP' title='Link to rs267607484'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS044963'><input type='submit' value='CS044963'></form></td><td>IVS3 ds G-A +1</td><td>c.735+1G>A</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14724127&amp;dopt=Abstract' target=ref>Goldfarb (2004) Brain <b>127,</b> 723</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22484823&amp;dopt=Abstract' target=ref>Gudkova (2013) <i>Pediatr Cardiol</i> <b>34:</b> 467</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285069'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS000452'><input type='submit' value='CS000452'></form></td><td>IVS3 ds A-G +3</td><td>c.735+3A>G</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10717012&amp;dopt=Abstract' target=ref>Dalakas (2000) N Engl J Med <b>342,</b> 770</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23155419&amp;dopt=Abstract' target=ref>McDonald (2012) <i>PLoS One</i> <b>7:</b> e48864</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285071'>GEN</span> <span class='cpg' title='causes deletion of exon 3 (delD214-E245).'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607483' target='dbSNP' title='Link to rs267607483'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS135499'><input type='submit' value='CS135499'></form></td><td>IVS7 as A-G -2</td><td>c.1289-2A>G</td><td>Muscular dystrophy, limb girdle 2</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23687351&amp;dopt=Abstract' target=ref>Cetin (2013) J Med Genet <b>50,</b> 437</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220290383'>GEN</span>  </td></tr>

</table><a name='dels'></a><h3 class='heading'>Small deletions : 9 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD deletion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD136434'><input type='submit' value='CD136434'></form></td><td>CCGGCTG^<sup><span class='td'><b>75</b></span></sup>GGGaCCACCCGCAC</td><td>c.226delA</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23575897&amp;dopt=Abstract' target=ref>Henderson (2013) Acta Neuropathol <b>125,</b> 917</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283410'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD105030'><input type='submit' value='CD105030'></form></td><td>GTGGAG^<sup><span class='td'><b>112</b></span></sup>CTGCagGAGCTCAATG</td><td>c.338_339delAG</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20696008&amp;dopt=Abstract' target=ref>Hong (2010) Neuropathol Appl Neurobiol <b>37,</b> 257</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20654101&amp;dopt=Abstract' target=ref>Hong (2010) <i>Zhonghua Xin Xue Guan Bing Za Zhi</i> <b>38:</b> 420</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283522-220283523'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs267607497' target='dbSNP' title='Link to rs267607497'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD101552'><input type='submit' value='CD101552'></form></td><td>GGAGCTG^<sup><span class='td'><b>113</b></span></sup>CAGgagCTCAATGACC</td><td>c.340_342delGAG</td><td>Desmin myopathy with cardiomyopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20133133&amp;dopt=Abstract' target=ref>Vernengo (2010) Neuromuscul Disord <b>20,</b> 178</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21262226&amp;dopt=Abstract' target=ref>Chourbagi (2011) <i>Exp Cell Res</i> <b>317:</b> 886</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22403400&amp;dopt=Abstract' target=ref>Brodehl (2012) <i>J Biol Chem</i> <b>287:</b> 16047</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220283524-220283526'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD136375'><input type='submit' value='CD136375'></form></td><td>AGATT^<sup><span class='td'><b>199</b></span></sup>CAGTTgAAGGAAGAAG</td><td>c.600delG</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23815709&amp;dopt=Abstract' target=ref>McLaughlin (2013) BMC Med Genet <b>14,</b> </a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220284838'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD036091'><input type='submit' value='CD036091'></form></td><td>CGTTC^<sup><span class='td'><b>239</b></span></sup>CTTAAgaaAGTGCATGAA</td><td>c.720_722delGAA</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12620971&amp;dopt=Abstract' target=ref>Schroder (2003) Hum Mol Genet <b>12,</b> 657</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=NO ID&amp;dopt=Abstract' target=ref>Schroder (2007) <i>Hum Mol Genet</i> <b>16:</b> 2989</a> [Additional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285053-220285055'>GEN</span> <span class='cpg' title='Descr. as c.5141_5143insA K239fs242.'>COM</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD066685'><input type='submit' value='CD066685'></form></td><td>CATGAA^<sup><span class='td'><b>245</b></span></sup>GAG_E3I3_GtataccttggCCCCTCTTCC</td><td>c.735+2_735+11del10</td><td>Cardiomyopathy, restrictive with atrioventricular block</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16376610&amp;dopt=Abstract' target=ref>Arbustini (2006) Eur J Heart Fail <b>8,</b> 477</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285070-220285079'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD103220'><input type='submit' value='CD103220'></form></td><td>GTCG^<sup><span class='td'><b>299</b></span></sup>AAG_E4I4_GTGggTGGCCTCGCC</td><td>c.897+4_897+5delGG</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20474083&amp;dopt=Abstract' target=ref>Zimmerman (2010) Genet Med <b>12,</b> 268</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220285382-220285383'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD040304'><input type='submit' value='CD040304'></form></td><td>ATTTGCC^<sup><span class='td'><b>358</b></span></sup>AGTgaggccagtGGCTACCAGG</td><td>c.1076_1084delAGGCCAGTG</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14648196&amp;dopt=Abstract' target=ref>Kaminska (2004) Hum Genet <b>114,</b> 306</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286114-220286122'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD040305'><input type='submit' value='CD040305'></form></td><td>TACCAG^<sup><span class='td'><b>365</b></span></sup>GACAacaTTGCGCGCCT</td><td>c.1097_1099delACA</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14648196&amp;dopt=Abstract' target=ref>Kaminska (2004) Hum Genet <b>114,</b> 306</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286135-220286137'>GEN</span>  </td></tr>

</table><a name='ins'></a><h3 class='heading'>Small insertions : 1 mutation <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD insertion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='oddR'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='I'><input type='hidden' name='acc' value='CI034607'><input type='submit' value='CI034607'></form></td><td>GCGTTC^<sup><span class='td'><b>239</b></span></sup>CTTAaAGAAAGTGCA</td><td>c.719dupA</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12620971&amp;dopt=Abstract' target=ref>Schröder (2003) Hum Mol Genet <b>12,</b> 657</a></td><td style='white-space:nowrap;'><span class='ret' title='Retired record'>R</span>  <span class='gen' title='Chr2:220285052-220285053'>GEN</span> <span class='cpg' title='often mis-named as 245X.  Actually causes PTC after codon 243. Corrected to deletion (CD036091), Schroder HMG 16, 2989 (2007)'>COM</span> </td></tr>

</table><a name='indels'></a><h3 class='heading'>Small indels : 2 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD deletion/insertion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='X'><input type='hidden' name='acc' value='CX129460'><input type='submit' value='CX129460'></form></td><td>GATGAGG^<sup><span class='td'><b>348</b></span></sup>CAGatgcgggaattggaggaccGATTTGCCAG<br><b>Ins:</b> g</td><td>c.1045_1063delins19</td><td>Atrioventricular block and mild myopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23036309&amp;dopt=Abstract' target=ref>Cao (2013) Clin Neuropathol <b>32,</b> 9</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286083-220286101'>GEN</span> <span class='cpg' title='aka p.Met349_Arg355del, insGly349.'>COM</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='X'><input type='hidden' name='acc' value='CX094917'><input type='submit' value='CX094917'></form></td><td>GGAGGGA^<sup><span class='td'><b>412</b></span></sup>GAGgaGAGCCG_E6I6_GTGA<br><b>Ins:</b> ag</td><td>c.1237_1238delGAinsAG</td><td>Myopathy, desmin related</td><td><a href='oops.php'>Dunand (2009) Neuromuscul Disord <b>19</b> 570</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr2:220286275-220286276'>GEN</span> <span class='cpg' title='Descr. as C.1323_1324GA > AG mutation in exon 6, mut. conf. by PC <916>.'>COM</span> </td></tr>

</table><a name='grdel'></a><h3 class='heading'>Gross deletions : 1 mutation <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>DNA<br>level</th><th>Description</th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='G'><input type='hidden' name='acc' value='CG984286'><input type='submit' value='CG984286'></form></td><td>gDNA</td><td>21 bp nt. 679 cd. 173</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9736733&amp;dopt=Abstract' target=ref>Munoz-Marmol (1998) Proc Natl Acad Sci U S A <b>95,</b> 11312</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19433360&amp;dopt=Abstract' target=ref>Piñol-Ripoll (2009) <i>Neuromuscul Disord</i> <b>19:</b> 418</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  </td></tr>

</table><hr><div class='bott2'>
Designed by P.D.Stenson HGMD&reg;<br><a class='black' href='copyright.php'>Copyright &copy; Cardiff University</a> 2013
</div>
<p class='spacer'></div></body></html>