<!DOCTYPE html><html><head><title>HGMD Mutation Result</title><link rel='stylesheet' type='text/css' href='css/global.css'><META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'></head><body>

<div class='sidemenu' id='opac'>
<div class='sidelink'><span class='a'>
<a class='sidebar' href='search_gene.php'>G</a><br>
<a class='sidebar' href='search_mut.php'>M</a><br>
<a class='sidebar' href='search_ref.php'>R</a><br>
<a class='sidebar' href='search_batch.php'>B</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>A</a><br><hr>
<a class='sidebar' href='stats.php'>S</a><br>
<a class='sidebar' href='info.php'>I</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>S</a><br>
<hr>
<a class='sidebar' href='start.php'>H</a><br>
</span><span class='b'>
<a class='sidebar' href='search_gene.php'>Gene</a><br>
<a class='sidebar' href='search_mut.php'>Mutation</a><br>
<a class='sidebar' href='search_ref.php'>Reference</a><br>
<a class='sidebar' href='search_batch.php'>Batch</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a><br><hr>
<a class='sidebar' href='stats.php'>Statistics</a><br>
<a class='sidebar' href='info.php'>Information</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a><br>
<hr>
<a class='sidebar' href='start.php'>Home</a><br>
</span>
</div>
</div><div class='top'><div class='logo1'><a href='http://www.hgmd.cf.ac.uk/' target='HGMDmain'><img id='hgmdlogo' src='bar/hgmd_new2.png' alt='HGMD'></a></div><div class='title'>HGMD&reg; Professional 2013.4 - 15<sup>th</sup> December 2013</div><div class='logo2'><a href='http://www.biobase-international.com' target='Biobase'><img src='bar/biobase_logo.png' alt='BioBase'></a></div><div class='links'> <a class='sidebar' href='search_gene.php'>Gene</a>
<a class='sidebar' href='search_mut.php'>Mutation</a>
<a class='sidebar' href='search_ref.php'>Reference</a>
<a class='sidebar' href='search_batch.php'>Batch</a> <a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a> | <a class='sidebar' href='stats.php'>Statistics</a>
<a class='sidebar' href='info.php'>Information</a>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a> |
<a class='sidebar' href='start.php'>Home</a></div></div><div class='content'><a name='top'></a><h3 class='heading'>All 71 mutations in <a href='gene.php?gene=ANO5'>ANO5</a></h3><table><tr class='odd'><td class='center'><a class='black' href='#miss/nons'>missense/nonsense</a></td><td class='center'><a class='black' href='#splice'>splicing</a></td><td class='center'><a class='black' href='#dels'>small deletions</a></td><td class='center'><a class='black' href='#ins'>small insertions</a></td><td class='center'><a class='black' href='#indels'>small indels</a></td><td class='center'><a class='black' href='#grdel'>gross deletions</a></td></tr></table><a name='miss/nons'></a><h3 class='heading'>Missense/nonsense : 46 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th><a href='useful.php#cods'>HGMD</a> codon<br>change</th><th><a href='useful.php#cods'>HGMD</a> amino<br>acid change</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(protein)</span></th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117893'><input type='submit' value='CM117893'></form></td>
	<td>gCGA-TGA</td><td>Arg50Term</td><td>c.148C>T</td><td>p.R50*</td><td>Myopathy / muscular dystrophy</td><td><a href='oops.php'>Behin (2011) Neuromuscul Disord <b>21</b> 675</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22239801'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1212692'><input type='submit' value='CM1212692'></form></td>
	<td>AAT-AGT</td><td>Asn52Ser</td><td>c.155A>G</td><td>p.N52S</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) Neuromuscul Disord <b>22S2,</b> S122</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) <i>Hum Mutat</i> <b>34:</b> 1111</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22239808'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs143777403' target='dbSNP' title='Link to rs143777403'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117895'><input type='submit' value='CM117895'></form></td>
	<td>gCGG-TGG</td><td>Arg58Trp</td><td>c.172C>T</td><td>p.R58W</td><td>Myopathy / muscular dystrophy</td><td><a href='oops.php'>Behin (2011) Neuromuscul Disord <b>21</b> 675</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) <i>J Neurol</i> <b>260:</b> 2084</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22239825'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs201725369' target='dbSNP' title='Link to rs201725369'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117897'><input type='submit' value='CM117897'></form></td>
	<td>cCGA-TGA</td><td>Arg74Term</td><td>c.220C>T</td><td>p.R74*</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='oops.php'>Magri (2011) Neuromuscul Disord <b>21</b> 675</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22242682'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM122322'><input type='submit' value='CM122322'></form></td>
	<td>GAT-GGT</td><td>Asp81Gly</td><td>c.242A>G</td><td>p.D81G</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22402862&amp;dopt=Abstract' target=ref>Penttilä (2012) Neurology <b>78,</b> 897</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22242704'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199501657' target='dbSNP' title='Link to rs199501657'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117899'><input type='submit' value='CM117899'></form></td>
	<td>GCGg-GCA</td><td>Ala98Ala</td><td>c.294G>A</td><td>p.A98A</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='oops.php'>Magri (2011) Neuromuscul Disord <b>21</b> 675</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22242756'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs142858990' target='dbSNP' title='Link to rs142858990'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117894'><input type='submit' value='CM117894'></form></td>
	<td>CTC-CGC</td><td>Leu108Arg</td><td>c.323T>G</td><td>p.L108R</td><td>Myopathy / muscular dystrophy</td><td><a href='oops.php'>Behin (2011) Neuromuscul Disord <b>21</b> 675</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) <i>Neuromuscul Disord</i> <b>22 Sup:</b> S122</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22247558'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136008'><input type='submit' value='CM136008'></form></td>
	<td>GGA-GTA</td><td>Gly126Val</td><td>c.377G>T</td><td>p.G126V</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) Neuromuscul Disord <b>23,</b> 456</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22248861'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM129936'><input type='submit' value='CM129936'></form></td>
	<td>gATC-TTC</td><td>Ile133Phe</td><td>c.397A>T</td><td>p.I133F</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22742934&amp;dopt=Abstract' target=ref>Magri (2012) Neuromuscul Disord <b>22,</b> 934</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22248881'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137895'><input type='submit' value='CM137895'></form></td>
	<td>CAT-CGT</td><td>His134Arg</td><td>c.401A>G</td><td>p.H134R</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22248885'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM128141'><input type='submit' value='CM128141'></form></td>
	<td>cCAT-TAT</td><td>His134Tyr</td><td>c.400C>T</td><td>p.H134Y</td><td>Myopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22527239&amp;dopt=Abstract' target=ref>Pénisson-Besnier (2012) J Neurol <b>259,</b> 1988</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) <i>Hum Mutat</i> <b>34:</b> 1111</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22248884'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM101058'><input type='submit' value='CM101058'></form></td>
	<td>GGG-GTG</td><td>Gly231Val</td><td>c.692G>T</td><td>p.G231V</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20096397&amp;dopt=Abstract' target=ref>Bolduc (2010) Am J Hum Genet <b>86,</b> 213</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22257752'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854523' target='dbSNP' title='Link to rs137854523'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117900'><input type='submit' value='CM117900'></form></td>
	<td>aGAA-AAA</td><td>Glu298Lys</td><td>c.892G>A</td><td>p.E298K</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='oops.php'>Magri (2011) Neuromuscul Disord <b>21</b> 675</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22271796'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136007'><input type='submit' value='CM136007'></form></td>
	<td>GGT-GTT</td><td>Gly301Val</td><td>c.902G>T</td><td>p.G301V</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) Neuromuscul Disord <b>23,</b> 456</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22271806'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM130567'><input type='submit' value='CM130567'></form></td>
	<td>TGT-TAT</td><td>Cys342Tyr</td><td>c.1025G>A</td><td>p.C342Y</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23169617&amp;dopt=Abstract' target=ref>Little (2013) Muscle Nerve <b>47,</b> 287</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22272298'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM041456'><input type='submit' value='CM041456'></form></td>
	<td>cTGT-CGT</td><td>Cys356Arg</td><td>c.1066T>C</td><td>p.C356R</td><td>Gnathodiaphyseal dysplasia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15124103&amp;dopt=Abstract' target=ref>Tsatsumi (2004) Am J Hum Genet <b>74,</b> 1255</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23843187&amp;dopt=Abstract' target=ref>Tran (2013) <i>J Cell Physiol</i> <b>:</b> </a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22272339'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs119103234' target='dbSNP' title='Link to rs119103234'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM041457'><input type='submit' value='CM041457'></form></td>
	<td>cTGT-GGT</td><td>Cys356Gly</td><td>c.1066T>G</td><td>p.C356G</td><td>Gnathodiaphyseal dysplasia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15124103&amp;dopt=Abstract' target=ref>Tsatsumi (2004) Am J Hum Genet <b>74,</b> 1255</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23843187&amp;dopt=Abstract' target=ref>Tran (2013) <i>J Cell Physiol</i> <b>:</b> </a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22272339'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs119103234' target='dbSNP' title='Link to rs119103234'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1212693'><input type='submit' value='CM1212693'></form></td>
	<td>AAT-AGT</td><td>Asn366Ser</td><td>c.1097A>G</td><td>p.N366S</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) Neuromuscul Disord <b>22S2,</b> S122</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22272370'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1212694'><input type='submit' value='CM1212694'></form></td>
	<td>aCGA-TGA</td><td>Arg404Term</td><td>c.1210C>T</td><td>p.R404*</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) Neuromuscul Disord <b>22S2,</b> S122</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22276946'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM124412'><input type='submit' value='CM124412'></form></td>
	<td>aCAG-TAG</td><td>Gln421Term</td><td>c.1261C>T</td><td>p.Q421*</td><td>Autism</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22542183&amp;dopt=Abstract' target=ref>Iossifov (2012) Neuron <b>74,</b> 285</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22276997'>GEN</span> <span class='cpg' title='Posn. conf. in Table S2 (online).'>COM</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137896'><input type='submit' value='CM137896'></form></td>
	<td>GCC-GAC</td><td>Ala464Asp</td><td>c.1391C>A</td><td>p.A464D</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22279284'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM134766'><input type='submit' value='CM134766'></form></td>
	<td>ACC-ATC</td><td>Thr513Ile</td><td>c.1538C>T</td><td>p.T513I</td><td>Gnathodiaphyseal dysplasia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23047743&amp;dopt=Abstract' target=ref>Marconi (2013) Eur J Hum Genet <b>21,</b> 613</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22281195'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865467' target='dbSNP' title='Link to rs281865467'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM117898'><input type='submit' value='CM117898'></form></td>
	<td>aTCT-CCT</td><td>Ser537Pro</td><td>c.1609T>C</td><td>p.S537P</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='oops.php'>Magri (2011) Neuromuscul Disord <b>21</b> 675</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22281266'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136996'><input type='submit' value='CM136996'></form></td>
	<td>ATGg-ATC</td><td>Met543Ile</td><td>c.1629G>C</td><td>p.M543I</td><td>Miyoshi distal myopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) J Neurol <b>260,</b> 2084</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22281286'>GEN</span> <span class='cpg' title='Reported as M543T, confirmed by PC <1630>'>COM</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136006'><input type='submit' value='CM136006'></form></td>
	<td>CGA-CAA</td><td>Arg547Gln</td><td>c.1640G>A</td><td>p.R547Q</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) Neuromuscul Disord <b>23,</b> 456</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22283684'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137908'><input type='submit' value='CM137908'></form></td>
	<td>tCGA-TGA</td><td>Arg547Term</td><td>c.1639C>T</td><td>p.R547*</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22283683'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM115441'><input type='submit' value='CM115441'></form></td>
	<td>ACA-ATA</td><td>Thr548Ile</td><td>c.1643C>T</td><td>p.T548I</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21739273&amp;dopt=Abstract' target=ref>Deschauer (2011) Nervenarzt <b>82,</b> 1596</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) <i>Neuromuscul Disord</i> <b>22 Sup:</b> S122</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22283687'>GEN</span> <span class='cpg' title='Also found in asymptomatic sister.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865465' target='dbSNP' title='Link to rs281865465'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136989'><input type='submit' value='CM136989'></form></td>
	<td>CAG-CTG</td><td>Gln564Leu</td><td>c.1691A>T</td><td>p.Q564L</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) J Neurol <b>260,</b> 2084</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22283735'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM110382'><input type='submit' value='CM110382'></form></td>
	<td>TTT-TCT</td><td>Phe578Ser</td><td>c.1733T>C</td><td>p.F578S</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21186264&amp;dopt=Abstract' target=ref>Hicks (2011) Brain <b>134,</b> 171</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=ABST&amp;dopt=Abstract' target=ref>Behin (2011) <i>Neuromuscul Disord</i> <b>21:</b> 675</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22283777'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854526' target='dbSNP' title='Link to rs137854526'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM134527'><input type='submit' value='CM134527'></form></td>
	<td>TGTg-TGA</td><td>Cys601Term</td><td>c.1803T>A</td><td>p.C601*</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23663589&amp;dopt=Abstract' target=ref>Liewluck (2013) Eur J Neurol <b>epub,</b> epub</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22284494'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137911'><input type='submit' value='CM137911'></form></td>
	<td>CGA-CTA</td><td>Arg642Leu</td><td>c.1925G>T</td><td>p.R642L</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22291884'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136009'><input type='submit' value='CM136009'></form></td>
	<td>TAT-TGT</td><td>Tyr652Cys</td><td>c.1955A>G</td><td>p.Y652C</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) Neuromuscul Disord <b>23,</b> 456</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22291914'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM122808'><input type='submit' value='CM122808'></form></td>
	<td>TGGg-TGC</td><td>Trp655Cys</td><td>c.1965G>C</td><td>p.W655C</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22499103&amp;dopt=Abstract' target=ref>Schessl (2012) Muscle Nerve <b>45,</b> 740</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22291924'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM110383'><input type='submit' value='CM110383'></form></td>
	<td>TAC-TGC</td><td>Tyr673Cys</td><td>c.2018A>G</td><td>p.Y673C</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21186264&amp;dopt=Abstract' target=ref>Hicks (2011) Brain <b>134,</b> 171</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) <i>J Neurol</i> <b>260:</b> 2084</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22291977'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854527' target='dbSNP' title='Link to rs137854527'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM122323'><input type='submit' value='CM122323'></form></td>
	<td>tAAT-GAT</td><td>Asn701Asp</td><td>c.2101A>G</td><td>p.N701D</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22402862&amp;dopt=Abstract' target=ref>Penttilä (2012) Neurology <b>78,</b> 897</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22294401'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865466' target='dbSNP' title='Link to rs281865466'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM122324'><input type='submit' value='CM122324'></form></td>
	<td>ACT-AGT</td><td>Thr714Ser</td><td>c.2141C>G</td><td>p.T714S</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22402862&amp;dopt=Abstract' target=ref>Penttilä (2012) Neurology <b>78,</b> 897</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22294441'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs200631556' target='dbSNP' title='Link to rs200631556'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM101061'><input type='submit' value='CM101061'></form></td>
	<td>cCGT-TGT</td><td>Arg758Cys</td><td>c.2272C>T</td><td>p.R758C</td><td>Miyoshi myopathy, non-dysferlin</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20096397&amp;dopt=Abstract' target=ref>Bolduc (2010) Am J Hum Genet <b>86,</b> 213</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) <i>Neuromuscul Disord</i> <b>22 Sup:</b> S122</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22296151'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854529' target='dbSNP' title='Link to rs137854529'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM1212695'><input type='submit' value='CM1212695'></form></td>
	<td>TCG-TTG</td><td>Ser796Leu</td><td>c.2387C>T</td><td>p.S796L</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) Neuromuscul Disord <b>22S2,</b> S122</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) <i>Hum Mutat</i> <b>34:</b> 1111</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22296266'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs61910685' target='dbSNP' title='Link to rs61910685'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137913'><input type='submit' value='CM137913'></form></td>
	<td>aCGA-TGA</td><td>Arg799Term</td><td>c.2395C>T</td><td>p.R799*</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22296274'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137914'><input type='submit' value='CM137914'></form></td>
	<td>TAC-TGC</td><td>Tyr806Cys</td><td>c.2417A>G</td><td>p.Y806C</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22297642'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM119397'><input type='submit' value='CM119397'></form></td>
	<td>TATc-TAA</td><td>Tyr811Term</td><td>c.2433T>A</td><td>p.Y811*</td><td>Myopathy / muscular dystrophy</td><td><a href='oops.php'>Behin (2011) Neuromuscul Disord <b>21</b> 675</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) <i>Neuromuscul Disord</i> <b>22 Sup:</b> S122</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) <i>Neuromuscul Disord</i> <b>23:</b> 456</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22297658'>GEN</span> <span class='cpg' title='Base change confirmed by PC <1291>'>COM</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM134528'><input type='submit' value='CM134528'></form></td>
	<td>ATG-AAG</td><td>Met833Lys</td><td>c.2498T>A</td><td>p.M833K</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23663589&amp;dopt=Abstract' target=ref>Liewluck (2013) Eur J Neurol <b>epub,</b> epub</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22297723'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs142073798' target='dbSNP' title='Link to rs142073798'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM129937'><input type='submit' value='CM129937'></form></td>
	<td>ATG-AGG</td><td>Met839Arg</td><td>c.2516T>G</td><td>p.M839R</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22742934&amp;dopt=Abstract' target=ref>Magri (2012) Neuromuscul Disord <b>22,</b> 934</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22297741'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137915'><input type='submit' value='CM137915'></form></td>
	<td>aCAT-GAT</td><td>His841Asp</td><td>c.2521C>G</td><td>p.H841D</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22301090'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM137918'><input type='submit' value='CM137918'></form></td>
	<td>aATC-CTC</td><td>Ile865Leu</td><td>c.2593A>C</td><td>p.I865L</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22301162'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM136991'><input type='submit' value='CM136991'></form></td>
	<td>cATG-CTG</td><td>Met900Leu</td><td>c.2698A>C</td><td>p.M900L</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) J Neurol <b>260,</b> 2084</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22301267'>GEN</span>  </td></tr>

</table><a name='splice'></a><h3 class='heading'>Splicing : 13 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>HGMD splicing mutation</th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS136005'><input type='submit' value='CS136005'></form></td><td>IVS1 as G-A -1</td><td>c.41-1G>A</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) Neuromuscul Disord <b>23,</b> 456</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22225349'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS122809'><input type='submit' value='CS122809'></form></td><td>IVS5 as G-A -1</td><td>c.295-1G>A</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22499103&amp;dopt=Abstract' target=ref>Schessl (2012) Muscle Nerve <b>45,</b> 740</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22247529'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS137921'><input type='submit' value='CS137921'></form></td><td>IVS8 ds G-A +1</td><td>c.762+1G>A</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22257823'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS129329'><input type='submit' value='CS129329'></form></td><td>IVS8 ds G-T +5</td><td>c.762+5G>T</td><td>Myopathy of posterior calf muscles, late-onset</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23050857&amp;dopt=Abstract' target=ref>Neusch (2012) J Med Case Rep <b>6,</b> </a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22257827'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS136990'><input type='submit' value='CS136990'></form></td><td>IVS11 as T-G -9</td><td>c.1120-9T>G</td><td>Miyoshi distal myopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) J Neurol <b>260,</b> 2084</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22272488'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS101060'><input type='submit' value='CS101060'></form></td><td>IVS13 ds C-G -38</td><td>c.1295C>G</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20096397&amp;dopt=Abstract' target=ref>Bolduc (2010) Am J Hum Genet <b>86,</b> 213</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22277031'>GEN</span> <span class='cpg' title='GCT>GGT, Ala432Gly.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854524' target='dbSNP' title='Link to rs137854524'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS122321'><input type='submit' value='CS122321'></form></td><td>IVS14 ds G-A +5</td><td>c.1407+5G>A</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22402862&amp;dopt=Abstract' target=ref>Penttilä (2012) Neurology <b>78,</b> 897</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22279305'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865464' target='dbSNP' title='Link to rs281865464'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS137922'><input type='submit' value='CS137922'></form></td><td>IVS14 ds G-T +5</td><td>c.1407+5G>T</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22279305'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS1212696'><input type='submit' value='CS1212696'></form></td><td>IVS15 as C-G -3</td><td>c.1631-3C>G</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) Neuromuscul Disord <b>22S2,</b> S122</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22283672'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS134529'><input type='submit' value='CS134529'></form></td><td>IVS17 ds G-A +1</td><td>c.1898+1G>A</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23663589&amp;dopt=Abstract' target=ref>Liewluck (2013) Eur J Neurol <b>epub,</b> epub</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23670307&amp;dopt=Abstract' target=ref>Witting (2013) <i>J Neurol</i> <b>260:</b> 2084</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22284590'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs142027093' target='dbSNP' title='Link to rs142027093'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS122325'><input type='submit' value='CS122325'></form></td><td>IVS17 as A-G -4</td><td>c.1899-4A>G</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22402862&amp;dopt=Abstract' target=ref>Penttilä (2012) Neurology <b>78,</b> 897</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22291854'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS137923'><input type='submit' value='CS137923'></form></td><td>IVS18 as G-T -1</td><td>c.2030-1G>T</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22294329'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS128142'><input type='submit' value='CS128142'></form></td><td>IVS19 ds G-A +1</td><td>c.2235+1G>A</td><td>Myopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22527239&amp;dopt=Abstract' target=ref>Pénisson-Besnier (2012) J Neurol <b>259,</b> 1988</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22294536'>GEN</span>  </td></tr>

</table><a name='dels'></a><h3 class='heading'>Small deletions : 5 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD deletion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD130568'><input type='submit' value='CD130568'></form></td><td>GTTGGAA^<sup><span class='td'><b>117</b></span></sup>ATAgAAGACAAAAG</td><td>c.352delG</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23169617&amp;dopt=Abstract' target=ref>Little (2013) Muscle Nerve <b>47,</b> 287</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22247587'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD122326'><input type='submit' value='CD122326'></form></td><td>GTCAAA^<sup><span class='td'><b>506</b></span></sup>AGCTtCCTTACTCCT</td><td>c.1520delT</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22402862&amp;dopt=Abstract' target=ref>Penttilä (2012) Neurology <b>78,</b> 897</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22980763&amp;dopt=Abstract' target=ref>Sarkozy (2012) <i>Neuromuscul Disord</i> <b>22 Sup:</b> S122</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22281177'>GEN</span> <span class='cpg' title='c.1502delT in ref. corrected to c.1520delT (erratum). '>COM</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD134530'><input type='submit' value='CD134530'></form></td><td>GACCC^<sup><span class='td'><b>667</b></span></sup>CTTGGgCTTTTCTATG</td><td>c.2004delG</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23663589&amp;dopt=Abstract' target=ref>Liewluck (2013) Eur J Neurol <b>epub,</b> epub</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22291963'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD105557'><input type='submit' value='CD105557'></form></td><td>AAATGCC^<sup><span class='td'><b>770</b></span></sup>ACAcaGCCTATGACA</td><td>c.2311_2312delCA</td><td>Muscular dystrophy</td><td><a href='oops.php'>Penttila (2010) Neuromuscul Disord <b>20</b> 608</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr11:22296190-22296191'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854528' target='dbSNP' title='Link to rs137854528'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD136010'><input type='submit' value='CD136010'></form></td><td>CAAAA^<sup><span class='td'><b>860</b></span></sup>GATGTtgtGGAGAGAATC</td><td>c.2583_2585delTGT</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23607914&amp;dopt=Abstract' target=ref>van der Kooi (2013) Neuromuscul Disord <b>23,</b> 456</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22301152-22301154'>GEN</span>  </td></tr>

</table><a name='ins'></a><h3 class='heading'>Small insertions : 3 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD insertion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='I'><input type='hidden' name='acc' value='CI101059'><input type='submit' value='CI101059'></form></td><td>TTCAA^<sup><span class='td'><b>63</b></span></sup>AAAAAaTCAGCAAAGC</td><td>c.191dupA</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20096397&amp;dopt=Abstract' target=ref>Bolduc (2010) Am J Hum Genet <b>86,</b> 213</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21186264&amp;dopt=Abstract' target=ref>Hicks (2011) <i>Brain</i> <b>134:</b> 171</a> [Additional report]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22336395&amp;dopt=Abstract' target=ref>Bouquet (2012) <i>Rev Neurol (Paris)</i> <b>168:</b> 135</a> [Additional phenotype]</span><br><span class='td'>2 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22242653-22242654'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854521' target='dbSNP' title='Link to rs137854521'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='I'><input type='hidden' name='acc' value='CI137924'><input type='submit' value='CI137924'></form></td><td>ATGGC^<sup><span class='td'><b>329</b></span></sup>TTATTtATCAATGGAA</td><td>c.989dupT</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22271893-22271894'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='I'><input type='hidden' name='acc' value='CI117901'><input type='submit' value='CI117901'></form></td><td>ATCACA^<sup><span class='td'><b>542</b></span></sup>AAAAaTGG_E13I13_GTAAGCT</td><td>c.1627dupA</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='oops.php'>Magri (2011) Neuromuscul Disord <b>21</b> 675</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22194990&amp;dopt=Abstract' target=ref>Gallardo (2011) <i>PLoS One</i> <b>6:</b> e29061</a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22281284-22281285'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865480' target='dbSNP' title='Link to rs281865480'><span class='dbs'>dbSNP</span></a> </td></tr>

</table><a name='indels'></a><h3 class='heading'>Small indels : 2 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD deletion/insertion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='X'><input type='hidden' name='acc' value='CX110384'><input type='submit' value='CX110384'></form></td><td>CTTTCA^<sup><span class='td'><b>463</b></span></sup>GGAGcCACAGTGACA<br><b>Ins:</b> at</td><td>c.1391delCinsAT</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21186264&amp;dopt=Abstract' target=ref>Hicks (2011) Brain <b>134,</b> 171</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22279284'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs137854525' target='dbSNP' title='Link to rs137854525'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='X'><input type='hidden' name='acc' value='CX137925'><input type='submit' value='CX137925'></form></td><td>CTCTTTTTTTttttattcttCAG_I19E20_^<sup><span class='td'><b>746</b></span></sup>GCCTTTA<br><b>Ins:</b> attcttctggc</td><td>c.2236-13_2236-4delins10</td><td>Muscular dystrophy, limb girdle 2L</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23606453&amp;dopt=Abstract' target=ref>Sarkozy (2013) Hum Mutat <b>34,</b> 1111</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:22296102-22296111'>GEN</span> <span class='cpg' title='c.2234-13_2236-4delinsATTCTTCTGGC'>COM</span> </td></tr>

</table><a name='grdel'></a><h3 class='heading'>Gross deletions : 2 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>DNA<br>level</th><th>Description</th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='G'><input type='hidden' name='acc' value='CG134531'><input type='submit' value='CG134531'></form></td><td>gDNA</td><td>~418 kb incl. entire gene</td><td>Muscular dystrophy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23663589&amp;dopt=Abstract' target=ref>Liewluck (2013) Eur J Neurol <b>20,</b> 1383</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='G'><input type='hidden' name='acc' value='CG117896'><input type='submit' value='CG117896'></form></td><td>gDNA</td><td>ex. 15-17</td><td>Myopathy / muscular dystrophy</td><td><a href='oops.php'>Behin (2011) Neuromuscul Disord <b>21</b> 675</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  </td></tr>

</table><hr><div class='bott2'>
Designed by P.D.Stenson HGMD&reg;<br><a class='black' href='copyright.php'>Copyright &copy; Cardiff University</a> 2013
</div>
<p class='spacer'></div></body></html>