<!DOCTYPE html><html><head><title>HGMD Mutation Result</title><link rel='stylesheet' type='text/css' href='css/global.css'><META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'></head><body>

<div class='sidemenu' id='opac'>
<div class='sidelink'><span class='a'>
<a class='sidebar' href='search_gene.php'>G</a><br>
<a class='sidebar' href='search_mut.php'>M</a><br>
<a class='sidebar' href='search_ref.php'>R</a><br>
<a class='sidebar' href='search_batch.php'>B</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>A</a><br><hr>
<a class='sidebar' href='stats.php'>S</a><br>
<a class='sidebar' href='info.php'>I</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>S</a><br>
<hr>
<a class='sidebar' href='start.php'>H</a><br>
</span><span class='b'>
<a class='sidebar' href='search_gene.php'>Gene</a><br>
<a class='sidebar' href='search_mut.php'>Mutation</a><br>
<a class='sidebar' href='search_ref.php'>Reference</a><br>
<a class='sidebar' href='search_batch.php'>Batch</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a><br><hr>
<a class='sidebar' href='stats.php'>Statistics</a><br>
<a class='sidebar' href='info.php'>Information</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a><br>
<hr>
<a class='sidebar' href='start.php'>Home</a><br>
</span>
</div>
</div><div class='top'><div class='logo1'><a href='http://www.hgmd.cf.ac.uk/' target='HGMDmain'><img id='hgmdlogo' src='bar/hgmd_new2.png' alt='HGMD'></a></div><div class='title'>HGMD&reg; Professional 2013.4 - 15<sup>th</sup> December 2013</div><div class='logo2'><a href='http://www.biobase-international.com' target='Biobase'><img src='bar/biobase_logo.png' alt='BioBase'></a></div><div class='links'> <a class='sidebar' href='search_gene.php'>Gene</a>
<a class='sidebar' href='search_mut.php'>Mutation</a>
<a class='sidebar' href='search_ref.php'>Reference</a>
<a class='sidebar' href='search_batch.php'>Batch</a> <a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a> | <a class='sidebar' href='stats.php'>Statistics</a>
<a class='sidebar' href='info.php'>Information</a>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a> |
<a class='sidebar' href='start.php'>Home</a></div></div><div class='content'><a name='top'></a><h3 class='heading'>All 41 mutations in <a href='gene.php?gene=CAV3'>CAV3</a></h3><table><tr class='odd'><td class='center'><a class='black' href='#miss/nons'>missense/nonsense</a></td><td class='center'><a class='black' href='#splice'>splicing</a></td><td class='center'><a class='black' href='#dels'>small deletions</a></td><td class='center'><a class='black' href='#ins'>small insertions</a></td><td class='center'><a class='black' href='#grdel'>gross deletions</a></td></tr></table><a name='miss/nons'></a><h3 class='heading'>Missense/nonsense : 35 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th><a href='useful.php#cods'>HGMD</a> codon<br>change</th><th><a href='useful.php#cods'>HGMD</a> amino<br>acid change</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(protein)</span></th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM077176'><input type='submit' value='CM077176'></form></td>
	<td>cGTC-CTC</td><td>Val14Leu</td><td>c.40G>C</td><td>p.V14L</td><td>Sudden infant death syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17275750&amp;dopt=Abstract' target=ref>Cronk (2007) Heart Rhythm <b>4,</b> 161</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23465283&amp;dopt=Abstract' target=ref>Andreasen (2013) <i>Can J Cardiol</i> <b>:</b> </a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775602'>GEN</span> <span class='cpg' title='Described as V14L, sequence in fig.1. ~fivefold increase in late sodium current compared with controls.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121909281' target='dbSNP' title='Link to rs121909281'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM003420'><input type='submit' value='CM003420'></form></td>
	<td>CGA-CAA</td><td>Arg27Gln</td><td>c.80G>A</td><td>p.R27Q</td><td>Isolated hyperCKaemia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10746614&amp;dopt=Abstract' target=ref>Carbone (2000) Neurology <b>54,</b> 1373</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15318349&amp;dopt=Abstract' target=ref>Fee (2004) <i>Muscle Nerve</i> <b>30:</b> 375</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20472890&amp;dopt=Abstract' target=ref>Brauers (2010) <i>Am J Pathol</i> <b>177:</b> 261</a> [Functional characterisation]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775642'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840778' target='dbSNP' title='Link to rs116840778'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM086745'><input type='submit' value='CM086745'></form></td>
	<td>cCGA-GGA</td><td>Arg27Gly</td><td>c.79C>G</td><td>p.R27G</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18671188&amp;dopt=Abstract' target=ref>Voermans (2008) Neuropediatrics <b>39,</b> 116</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775641'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476324' target='dbSNP' title='Link to rs199476324'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM030376'><input type='submit' value='CM030376'></form></td>
	<td>GACc-GAA</td><td>Asp28Glu</td><td>c.84C>A</td><td>p.D28E</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12557291&amp;dopt=Abstract' target=ref>Fischer (2003) Ann Neurol <b>53,</b> 233</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21294223&amp;dopt=Abstract' target=ref>Ullrich (2011) <i>Hum Mutat</i> <b>32:</b> 309</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775646'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840782' target='dbSNP' title='Link to rs116840782'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM023343'><input type='submit' value='CM023343'></form></td>
	<td>CCC-CTC</td><td>Pro29Leu</td><td>c.86C>T</td><td>p.P29L</td><td>Isolated hyperCKaemia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12082049&amp;dopt=Abstract' target=ref>Merlini (2002) J Neurol Neurosurg Psychiatry <b>73,</b> 65</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20472890&amp;dopt=Abstract' target=ref>Brauers (2010) <i>Am J Pathol</i> <b>177:</b> 261</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775648'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840786' target='dbSNP' title='Link to rs116840786'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM043263'><input type='submit' value='CM043263'></form></td>
	<td>cCCC-ACC</td><td>Pro29Thr</td><td>c.85C>A</td><td>p.P29T</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15314133&amp;dopt=Abstract' target=ref>Van den Bergh (2004) J Neurol Neurosurg Psychiatry <b>75,</b> 1349</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775647'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840785' target='dbSNP' title='Link to rs116840785'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM043264'><input type='submit' value='CM043264'></form></td>
	<td>AACg-AAG</td><td>Asn33Lys</td><td>c.99C>G</td><td>p.N33K</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15564037&amp;dopt=Abstract' target=ref>Sugie (2004) Neuromuscul Disord <b>14,</b> 810</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775661'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs1008642' target='dbSNP' title='Link to rs1008642'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM080127'><input type='submit' value='CM080127'></form></td>
	<td>cGAG-AAG</td><td>Glu34Lys</td><td>c.100G>A</td><td>p.E34K</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17897828&amp;dopt=Abstract' target=ref>Lo (2008) Neuromuscul Disord <b>18,</b> 34</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775662'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476325' target='dbSNP' title='Link to rs199476325'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM043265'><input type='submit' value='CM043265'></form></td>
	<td>GTG-GAG</td><td>Val44Glu</td><td>c.131T>A</td><td>p.V44E</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15564037&amp;dopt=Abstract' target=ref>Sugie (2004) Neuromuscul Disord <b>14,</b> 810</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787228'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840788' target='dbSNP' title='Link to rs116840788'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM003421'><input type='submit' value='CM003421'></form></td>
	<td>cGCA-ACA</td><td>Ala46Thr</td><td>c.136G>A</td><td>p.A46T</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11001938&amp;dopt=Abstract' target=ref>Herrmann (2000) Hum Mol Genet <b>9,</b> 2335</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20472890&amp;dopt=Abstract' target=ref>Brauers (2010) <i>Am J Pathol</i> <b>177:</b> 261</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21660982&amp;dopt=Abstract' target=ref>Arias Gómez (2011) <i>Muscle Nerve</i> <b>44:</b> 126</a> [Additional phenotype]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787233'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840789' target='dbSNP' title='Link to rs116840789'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM012082'><input type='submit' value='CM012082'></form></td>
	<td>GCA-GTA</td><td>Ala46Val</td><td>c.137C>T</td><td>p.A46V</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11431690&amp;dopt=Abstract' target=ref>Betz (2001) Nat Genet <b>28,</b> 218</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787234'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840773' target='dbSNP' title='Link to rs116840773'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM072921'><input type='submit' value='CM072921'></form></td>
	<td>GAG-GCG</td><td>Glu47Ala</td><td>c.140A>C</td><td>p.E47A</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17405141&amp;dopt=Abstract' target=ref>Lorenzoni (2007) Muscle Nerve <b>36,</b> 258</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787237'>GEN</span> <span class='cpg' title='Descr. as A140C Glu47Ala, seq. in Fig. 2.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476327' target='dbSNP' title='Link to rs199476327'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM082523'><input type='submit' value='CM082523'></form></td>
	<td>GAGc-GAT</td><td>Glu47Asp</td><td>c.141G>T</td><td>p.E47D</td><td>Caveolinopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18583131&amp;dopt=Abstract' target=ref>Aboumousa (2008) Neuromuscul Disord <b>18,</b> 572</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787238'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476328' target='dbSNP' title='Link to rs199476328'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM058242'><input type='submit' value='CM058242'></form></td>
	<td>aGAG-AAG</td><td>Glu47Lys</td><td>c.139G>A</td><td>p.E47K</td><td>Rippling muscle disease & toe walking</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16247063&amp;dopt=Abstract' target=ref>Madrid (2005) Neurology <b>65,</b> 1301</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787236'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840793' target='dbSNP' title='Link to rs116840793'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM065054'><input type='submit' value='CM065054'></form></td>
	<td>cAGC-GGC</td><td>Ser53Gly</td><td>c.157A>G</td><td>p.S53G</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16458928&amp;dopt=Abstract' target=ref>Dotti (2006) J Neurol Sci <b>243,</b> 61</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787254'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840794' target='dbSNP' title='Link to rs116840794'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980305'><input type='submit' value='CM980305'></form></td>
	<td>cGGC-AGC</td><td>Gly56Ser</td><td>c.166G>A</td><td>p.G56S</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9536092&amp;dopt=Abstract' target=ref>McNally (1998) Hum Mol Genet <b>7,</b> 871</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11251997&amp;dopt=Abstract' target=ref>de Paula (2001) <i>Am J Med Genet</i> <b>99:</b> 303</a> [Additional report]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20472890&amp;dopt=Abstract' target=ref>Brauers (2010) <i>Am J Pathol</i> <b>177:</b> 261</a> [Functional characterisation]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr3:8787263'>GEN</span> <span class='cpg' title='not found in controls.'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs72546667' target='dbSNP' title='Link to rs72546667'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.032 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM040985'><input type='submit' value='CM040985'></form></td>
	<td>cGTG-ATG</td><td>Val57Met</td><td>c.169G>A</td><td>p.V57M</td><td>Isolated hyperCKaemia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15099591&amp;dopt=Abstract' target=ref>Alias (2004) Neuromuscul Disord <b>14,</b> 321</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22581547&amp;dopt=Abstract' target=ref>Milone (2012) <i>Muscle Nerve</i> <b>45:</b> 897</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787266'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840795' target='dbSNP' title='Link to rs116840795'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM050192'><input type='submit' value='CM050192'></form></td>
	<td>AGCt-AGA</td><td>Ser61Arg</td><td>c.183C>A</td><td>p.S61R</td><td>Myopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=15580566&amp;dopt=Abstract' target=ref>Fulizio (2005) Hum Mutat <b>25,</b> 82</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787280'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840796' target='dbSNP' title='Link to rs116840796'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM015309'><input type='submit' value='CM015309'></form></td>
	<td>cACC-CCC</td><td>Thr64Pro</td><td>c.190A>C</td><td>p.T64P</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11532985&amp;dopt=Abstract' target=ref>Matsuda (2001) Hum Mol Genet <b>10,</b> 1761</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787287'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476332' target='dbSNP' title='Link to rs199476332'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM041743'><input type='submit' value='CM041743'></form></td>
	<td>ACC-AGC</td><td>Thr64Ser</td><td>c.191C>G</td><td>p.T64S</td><td>Hypertrophic cardiomyopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14672715&amp;dopt=Abstract' target=ref>Hayashi (2004) Biochem Biophys Res Commun <b>313,</b> 178</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787288'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121909280' target='dbSNP' title='Link to rs121909280'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM072922'><input type='submit' value='CM072922'></form></td>
	<td>TGG-TAG</td><td>Trp71Term</td><td>c.212G>A</td><td>p.W71*</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17537631&amp;dopt=Abstract' target=ref>Ueyama (2007) Neuromuscul Disord <b>17,</b> 558</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787309'>GEN</span> <span class='cpg' title='Descr. as Trp to stop at codon 70 creating SpeI site.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476333' target='dbSNP' title='Link to rs199476333'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980306'><input type='submit' value='CM980306'></form></td>
	<td>TGCt-TGG</td><td>Cys72Trp</td><td>c.216C>G</td><td>p.C72W</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9536092&amp;dopt=Abstract' target=ref>McNally (1998) Hum Mol Genet <b>7,</b> 871</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11251997&amp;dopt=Abstract' target=ref>de Paula (2001) <i>Am J Med Genet</i> <b>99:</b> 303</a> [Additional report]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23465283&amp;dopt=Abstract' target=ref>Andreasen (2013) <i>Can J Cardiol</i> <b>:</b> </a> [Additional report]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787313'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840776' target='dbSNP' title='Link to rs116840776'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.002 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM082524'><input type='submit' value='CM082524'></form></td>
	<td>TAC-TGC</td><td>Tyr73Cys</td><td>c.218A>G</td><td>p.Y73C</td><td>Caveolinopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18583131&amp;dopt=Abstract' target=ref>Aboumousa (2008) Neuromuscul Disord <b>18,</b> 572</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787315'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476334' target='dbSNP' title='Link to rs199476334'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM085304'><input type='submit' value='CM085304'></form></td>
	<td>ACG-AAG</td><td>Thr78Lys</td><td>c.233C>A</td><td>p.T78K</td><td>Isolated hyperCKaemia</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18253147&amp;dopt=Abstract' target=ref>Traverso (2008) Lab Invest <b>88,</b> 275</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787330'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs72546668' target='dbSNP' title='Link to rs72546668'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.002 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM065052'><input type='submit' value='CM065052'></form></td>
	<td>ACG-ATG</td><td>Thr78Met</td><td>c.233C>T</td><td>p.T78M</td><td>Long QT syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17060380&amp;dopt=Abstract' target=ref>Vatta (2006) Circulation <b>114,</b> 2104</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17275750&amp;dopt=Abstract' target=ref>Cronk (2007) <i>Heart Rhythm</i> <b>4:</b> 161</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18253147&amp;dopt=Abstract' target=ref>Traverso (2008) <i>Lab Invest</i> <b>88:</b> 275</a> [Functional characterisation]</span><br><span class='td'>8 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787330'>GEN</span> <span class='cpg' title='Descr. as T78M, seq. in Fig. 1. '>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs72546668' target='dbSNP' title='Link to rs72546668'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.002 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM077177'><input type='submit' value='CM077177'></form></td>
	<td>CTG-CGG</td><td>Leu79Arg</td><td>c.236T>G</td><td>p.L79R</td><td>Sudden infant death syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17275750&amp;dopt=Abstract' target=ref>Cronk (2007) Heart Rhythm <b>4,</b> 161</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787333'>GEN</span> <span class='cpg' title='Described as L79R, sequence in fig.1. ~fivefold increase in late sodium current compared with controls.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs121909282' target='dbSNP' title='Link to rs121909282'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM139930'><input type='submit' value='CM139930'></form></td>
	<td>cGTC-ATC</td><td>Val82Ile</td><td>c.244G>A</td><td>p.V82I</td><td>Long QT syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23631430&amp;dopt=Abstract' target=ref>Lieve (2013) Genet Test Mol Biomarkers <b>17,</b> 553</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787341'>GEN</span> <span class='cpg' title='Descr. in Suppl. Table 1 (online).'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM065055'><input type='submit' value='CM065055'></form></td>
	<td>gGCC-ACC</td><td>Ala85Thr</td><td>c.253G>A</td><td>p.A85T</td><td>Long QT syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17060380&amp;dopt=Abstract' target=ref>Vatta (2006) Circulation <b>114,</b> 2104</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787350'>GEN</span> <span class='cpg' title='Descr. as A85T, seq. in Fig. 1.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs104893715' target='dbSNP' title='Link to rs104893715'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM030811'><input type='submit' value='CM030811'></form></td>
	<td>CTC-CCC</td><td>Leu87Pro</td><td>c.260T>C</td><td>p.L87P</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12666119&amp;dopt=Abstract' target=ref>Kubisch (2003) Ann Neurol <b>53,</b> 512</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787357'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs28936685' target='dbSNP' title='Link to rs28936685'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM030812'><input type='submit' value='CM030812'></form></td>
	<td>cGCC-ACC</td><td>Ala93Thr</td><td>c.277G>A</td><td>p.A93T</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=12666119&amp;dopt=Abstract' target=ref>Kubisch (2003) Ann Neurol <b>53,</b> 512</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=ABST&amp;dopt=Abstract' target=ref>Hankiewicz (2011) <i>Neuromuscul Disord</i> <b>21:</b> 669</a> [Additional phenotype]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787374'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs28936686' target='dbSNP' title='Link to rs28936686'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM065056'><input type='submit' value='CM065056'></form></td>
	<td>TTC-TGC</td><td>Phe97Cys</td><td>c.290T>G</td><td>p.F97C</td><td>Long QT syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17060380&amp;dopt=Abstract' target=ref>Vatta (2006) Circulation <b>114,</b> 2104</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23640888&amp;dopt=Abstract' target=ref>Vaidyanathan (2013) <i>J Biol Chem</i> <b>288:</b> 17472</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787387'>GEN</span> <span class='cpg' title='Descr. as F97C, seq. in Fig. 1.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs104893714' target='dbSNP' title='Link to rs104893714'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM082522'><input type='submit' value='CM082522'></form></td>
	<td>cTGG-CGG</td><td>Trp101Arg</td><td>c.301T>C</td><td>p.W101R</td><td>Caveolinopathy</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18583131&amp;dopt=Abstract' target=ref>Aboumousa (2008) Neuromuscul Disord <b>18,</b> 572</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787398'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476337' target='dbSNP' title='Link to rs199476337'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980307'><input type='submit' value='CM980307'></form></td>
	<td>CCA-CTA</td><td>Pro105Leu</td><td>c.314C>T</td><td>p.P105L</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9537420&amp;dopt=Abstract' target=ref>Minetti (1998) Nat Genet <b>18,</b> 365</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18509671&amp;dopt=Abstract' target=ref>Weiss (2008) <i>Pflugers Arch</i> <b>457:</b> 361</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19238754&amp;dopt=Abstract' target=ref>Ye (2008) <i>Biochemistry</i> <b>47:</b> 12312</a> [Functional characterisation]</span><br><span class='td'>2 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787411'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840805' target='dbSNP' title='Link to rs116840805'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM010790'><input type='submit' value='CM010790'></form></td>
	<td>CGC-CAC</td><td>Arg126His</td><td>c.377G>A</td><td>p.R126H</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11251997&amp;dopt=Abstract' target=ref>de Paula (2001) Am J Med Genet <b>99,</b> 303</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation ?'>DM?</span>  <span class='gen' title='Chr3:8787474'>GEN</span> <span class='cpg' title='found in two unaffected siblings.'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840777' target='dbSNP' title='Link to rs116840777'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM065053'><input type='submit' value='CM065053'></form></td>
	<td>AGCa-AGG</td><td>Ser141Arg</td><td>c.423C>G</td><td>p.S141R</td><td>Long QT syndrome</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17060380&amp;dopt=Abstract' target=ref>Vatta (2006) Circulation <b>114,</b> 2104</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787520'>GEN</span> <span class='cpg' title='Descr. as S141R, seq. in Fig. 1.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs104893713' target='dbSNP' title='Link to rs104893713'><span class='dbs'>dbSNP</span></a> </td></tr>

</table><a name='splice'></a><h3 class='heading'>Splicing : 1 mutation <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>HGMD splicing mutation</th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='S'><input type='hidden' name='acc' value='CS064375'><input type='submit' value='CS064375'></form></td><td>IVS1 ds T-C +2</td><td>c.114+2T>C</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16730439&amp;dopt=Abstract' target=ref>Muller (2006) Neuromuscul Disord <b>16,</b> 432</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21294223&amp;dopt=Abstract' target=ref>Ullrich (2011) <i>Hum Mutat</i> <b>32:</b> 309</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775678'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs116840787' target='dbSNP' title='Link to rs116840787'><span class='dbs'>dbSNP</span></a> </td></tr>

</table><a name='dels'></a><h3 class='heading'>Small deletions : 3 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD deletion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD982534'><input type='submit' value='CD982534'></form></td><td>TGAGC^<sup><span class='td'><b>62</b></span></sup>TACACcaccttcacTGTCTCCAAG</td><td>c.189_197delCACCTTCAC</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9537420&amp;dopt=Abstract' target=ref>Minetti (1998) Nat Genet <b>18,</b> 365</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787286-8787294'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476331' target='dbSNP' title='Link to rs199476331'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD034765'><input type='submit' value='CD034765'></form></td><td>CTGCATC^<sup><span class='td'><b>96</b></span></sup>TCCttcTGCCACATCT</td><td>c.290_292delTCT</td><td>Muscular dystrophy, limb girdle</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14663034&amp;dopt=Abstract' target=ref>Cagliani (2003) Neurology <b>61,</b> 1513</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787387-8787389'>GEN</span> <span class='cpg' title='also causes hyperCKaemia and rippling muscle dis.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476335' target='dbSNP' title='Link to rs199476335'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD076767'><input type='submit' value='CD076767'></form></td><td>CATCTGG^<sup><span class='td'><b>102</b></span></sup>GCGgtggtgCCATGCATTA</td><td>c.307_312delGTGGTG</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17524427&amp;dopt=Abstract' target=ref>Bae (2007) J Neurol Sci <b>260,</b> 275</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8787404-8787409'>GEN</span> <span class='cpg' title='Descr. as c.307_312delGTGGTG; Phe103_Phe104del.'>COM</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs199476338' target='dbSNP' title='Link to rs199476338'><span class='dbs'>dbSNP</span></a> </td></tr>

</table><a name='ins'></a><h3 class='heading'>Small insertions : 1 mutation <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD insertion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='I'><input type='hidden' name='acc' value='CI082234'><input type='submit' value='CI082234'></form></td><td>ATGGCA^<sup><span class='td'><b>4</b></span></sup>GAAGgAGCACACAGA</td><td>c.13dupG</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18487559&amp;dopt=Abstract' target=ref>Traverso (2008) J Neurol Neurosurg Psychiatry <b>79,</b> 735</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr3:8775575-8775576'>GEN</span> <span class='cpg' title='Descr. as c.13insG p.E4fs22X. Seq. in Fig. 1C.'>COM</span> </td></tr>

</table><a name='grdel'></a><h3 class='heading'>Gross deletions : 1 mutation <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>DNA<br>level</th><th>Description</th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='G'><input type='hidden' name='acc' value='CG082339'><input type='submit' value='CG082339'></form></td><td>gDNA</td><td>~80 kb incl. ex. 2 and OXTR</td><td>Rippling muscle disease</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18487559&amp;dopt=Abstract' target=ref>Traverso (2008) J Neurol Neurosurg Psychiatry <b>79,</b> 735</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  </td></tr>

</table><hr><div class='bott2'>
Designed by P.D.Stenson HGMD&reg;<br><a class='black' href='copyright.php'>Copyright &copy; Cardiff University</a> 2013
</div>
<p class='spacer'></div></body></html>