<!DOCTYPE html><html><head><title>HGMD Mutation Result</title><link rel='stylesheet' type='text/css' href='css/global.css'><META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=UTF-8'></head><body>

<div class='sidemenu' id='opac'>
<div class='sidelink'><span class='a'>
<a class='sidebar' href='search_gene.php'>G</a><br>
<a class='sidebar' href='search_mut.php'>M</a><br>
<a class='sidebar' href='search_ref.php'>R</a><br>
<a class='sidebar' href='search_batch.php'>B</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>A</a><br><hr>
<a class='sidebar' href='stats.php'>S</a><br>
<a class='sidebar' href='info.php'>I</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>S</a><br>
<hr>
<a class='sidebar' href='start.php'>H</a><br>
</span><span class='b'>
<a class='sidebar' href='search_gene.php'>Gene</a><br>
<a class='sidebar' href='search_mut.php'>Mutation</a><br>
<a class='sidebar' href='search_ref.php'>Reference</a><br>
<a class='sidebar' href='search_batch.php'>Batch</a><br><a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a><br><hr>
<a class='sidebar' href='stats.php'>Statistics</a><br>
<a class='sidebar' href='info.php'>Information</a><br>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a><br>
<hr>
<a class='sidebar' href='start.php'>Home</a><br>
</span>
</div>
</div><div class='top'><div class='logo1'><a href='http://www.hgmd.cf.ac.uk/' target='HGMDmain'><img id='hgmdlogo' src='bar/hgmd_new2.png' alt='HGMD'></a></div><div class='title'>HGMD&reg; Professional 2013.4 - 15<sup>th</sup> December 2013</div><div class='logo2'><a href='http://www.biobase-international.com' target='Biobase'><img src='bar/biobase_logo.png' alt='BioBase'></a></div><div class='links'> <a class='sidebar' href='search_gene.php'>Gene</a>
<a class='sidebar' href='search_mut.php'>Mutation</a>
<a class='sidebar' href='search_ref.php'>Reference</a>
<a class='sidebar' href='search_batch.php'>Batch</a> <a class='sidebar' href='http://portal.biobase-international.com:80/advanced/begin.html' target='advancedMain'>Advanced</a> | <a class='sidebar' href='stats.php'>Statistics</a>
<a class='sidebar' href='info.php'>Information</a>
<a class='sidebar' href='http://www.biobase-international.com/support' target='Support'>Support</a> |
<a class='sidebar' href='start.php'>Home</a></div></div><div class='content'><a name='top'></a><h3 class='heading'>All 19 mutations in <a href='gene.php?gene=CRYAB'>CRYAB</a></h3><table><tr class='odd'><td class='center'><a class='black' href='#miss/nons'>missense/nonsense</a></td><td class='center'><a class='black' href='#reg'>regulatory</a></td><td class='center'><a class='black' href='#dels'>small deletions</a></td></tr></table><a name='miss/nons'></a><h3 class='heading'>Missense/nonsense : 13 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th><a href='useful.php#cods'>HGMD</a> codon<br>change</th><th><a href='useful.php#cods'>HGMD</a> amino<br>acid change</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th>
<th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(protein)</span></th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM094270'><input type='submit' value='CM094270'></form></td>
	<td>CGC-CAC</td><td>Arg11His</td><td>c.32G>A</td><td>p.R11H</td><td>Cataract, congenital nuclear</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19597569&amp;dopt=Abstract' target=ref>Chen (2009) Mol Vis <b>15,</b> 1359</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21087083&amp;dopt=Abstract' target=ref>Chen (2010) <i>Biol Chem</i> <b>391:</b> 1391</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111782417'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM062567'><input type='submit' value='CM062567'></form></td>
	<td>cCCC-TCC</td><td>Pro20Ser</td><td>c.58C>T</td><td>p.P20S</td><td>Posterior polar cataract</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16877416&amp;dopt=Abstract' target=ref>Liu (2006) Invest Ophthalmol Vis Sci <b>47,</b> 3461</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111782391'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM132030'><input type='submit' value='CM132030'></form></td>
	<td>cCAG-TAG</td><td>Gln26Term</td><td>c.76C>T</td><td>p.Q26*</td><td>Cardiomyopathy, hypertrophic</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23197161&amp;dopt=Abstract' target=ref>Jensen (2013) Circulation <b>127,</b> 48</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111782373'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM092933'><input type='submit' value='CM092933'></form></td>
	<td>gCGG-TGG</td><td>Arg56Trp</td><td>c.166C>T</td><td>p.R56W</td><td>Cataract, juvenile</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19461931&amp;dopt=Abstract' target=ref>Safieh (2009) Mol Vis <b>15,</b> 980</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111782283'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM116555'><input type='submit' value='CM116555'></form></td>
	<td>gCGC-TGC</td><td>Arg69Cys</td><td>c.205C>T</td><td>p.R69C</td><td>Cataract, congenital</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21866213&amp;dopt=Abstract' target=ref>Sun (2011) Mol Vis <b>17,</b> 2197</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111781170'>GEN</span>  <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs139750142' target='dbSNP' title='Link to rs139750142'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM120280'><input type='submit' value='CM120280'></form></td>
	<td>gGAT-CAT</td><td>Asp109His</td><td>c.325G>C</td><td>p.D109H</td><td>Myofibrillar myopathy, cardiomyopathy & posterior polar cataract</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21920752&amp;dopt=Abstract' target=ref>Sacconi (2012) Neuromuscul Disord <b>22,</b> 66</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779691'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM980447'><input type='submit' value='CM980447'></form></td>
	<td>cAGG-GGG</td><td>Arg120Gly</td><td>c.358A>G</td><td>p.R120G</td><td>Myopathy, desmin related</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=9731540&amp;dopt=Abstract' target=ref>Vicart (1998) Nat Genet <b>20,</b> 92</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=10339554&amp;dopt=Abstract' target=ref>Bova (1999) <i>Proc Natl Acad Sci U S A</i> <b>96:</b> 6137</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16483541&amp;dopt=Abstract' target=ref>Inagaki (2006) <i>Biochem Biophys Res Commun</i> <b>342:</b> 379</a> [Functional characterisation]</span><br><span class='td'>7 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779658'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs104894201' target='dbSNP' title='Link to rs104894201'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM127955'><input type='submit' value='CM127955'></form></td>
	<td>TCA-TAA</td><td>Ser135Term</td><td>c.404C>A</td><td>p.S135*</td><td>Muscular dystrophy, hypertonic fatal infantile</td><td><a href='oops.php'>Tesi Rocha (2012) Neuromuscul Disord <b>22</b> 821</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779612'>GEN</span>  </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM060949'><input type='submit' value='CM060949'></form></td>
	<td>tGAT-AAT</td><td>Asp140Asn</td><td>c.418G>A</td><td>p.D140N</td><td>Cataract, lamellar</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16505043&amp;dopt=Abstract' target=ref>Liu (2006) Invest Ophthalmol Vis Sci <b>47,</b> 1069</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779598'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM033599'><input type='submit' value='CM033599'></form></td>
	<td>aCAG-TAG</td><td>Gln151Term</td><td>c.451C>T</td><td>p.Q151*</td><td>Myopathy, myofibrillar</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14681890&amp;dopt=Abstract' target=ref>Selcen (2003) Ann Neurol <b>54,</b> 804</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779565'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs104894202' target='dbSNP' title='Link to rs104894202'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM062568'><input type='submit' value='CM062568'></form></td>
	<td>tGGC-AGC</td><td>Gly154Ser</td><td>c.460G>A</td><td>p.G154S</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16793013&amp;dopt=Abstract' target=ref>Pilotto (2006) Biochem Biophys Res Commun <b>346,</b> 1115</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=20171888&amp;dopt=Abstract' target=ref>Reilich (2010) <i>Neuromuscul Disord</i> <b>20:</b> 255</a> [Additional phenotype]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=22995991&amp;dopt=Abstract' target=ref>Berg (2013) <i>Genet Med</i> <b>15:</b> 36</a> [Additional report]</span><br><span class='td'>2 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779556'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs150516929' target='dbSNP' title='Link to rs150516929'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM060948'><input type='submit' value='CM060948'></form></td>
	<td>CGC-CAC</td><td>Arg157His</td><td>c.470G>A</td><td>p.R157H</td><td>Cardiomyopathy, dilated</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=16483541&amp;dopt=Abstract' target=ref>Inagaki (2006) Biochem Biophys Res Commun <b>342,</b> 379</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=19282282&amp;dopt=Abstract' target=ref>Zhu (2009) <i>J Biol Chem</i> <b>284:</b> 13914</a> [Functional characterisation]</span><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br><span class='td'>1 more reference(s)...</span></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779546'>GEN</span> <span class='cpg' title='includes functional study'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span>  <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs141638421' target='dbSNP' title='Link to rs141638421'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.001 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='M'>
	<input type='hidden' name='gene_id' value=''><input type='hidden' name='sorted' value=''><input type='hidden' name='snp' value=''>
	<input type='hidden' name='acc' value='CM082584'><input type='submit' value='CM082584'></form></td>
	<td>cGCA-ACA</td><td>Ala171Thr</td><td>c.511G>A</td><td>p.A171T</td><td>Cataract, pediatric</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=18587492&amp;dopt=Abstract' target=ref>Devi (2008) Mol Vis <b>14,</b> 1157</a><br><span class='td'><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=23194663&amp;dopt=Abstract' target=ref>Raju (2013) <i>Biochem Biophys Res Commun</i> <b>430:</b> 107</a> [Functional characterisation]</span><br></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779505'>GEN</span> <span class='cpg' title='Descr. as c.557G>A A171T.'>COM</span> <span class='cpg' title='Mutation may have occured by deamination of methylated CpG dinucleotide'>CpG</span> </td></tr>

</table><a name='reg'></a><h3 class='heading'>Regulatory : 2 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th><th>Regulatory sequence</th>
<th>Phenotype</th><th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='R'><input type='hidden' name='acc' value='CR033143'><input type='submit' value='CR033143'></form></td><td nowrap>TGGATTTAATGTTCTGAGAGCCACATAGAA(G-C)GAAAGATGCAAGAAATCTGTTTGCTCTTTT<br>-650 relative to initiation codon</td><td>Multiple sclerosis, susceptibility, association with</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14610128&amp;dopt=Abstract' target=ref>Van Veen (2003) Neurology <b>61,</b> 1245</a></td><td style='white-space:nowrap;'><span class='fp' title='Disease-associated polymorphism'>DP</span>  <span class='gen' title='Chr11:111783098'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs2234702' target='dbSNP' title='Link to rs2234702'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.004 MAF source=1000 Genomes'>FREQ</a></td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='R'><input type='hidden' name='acc' value='CR076690'><input type='submit' value='CR076690'></form></td><td nowrap>GGTGTGGACAGAAAGCTAGTGAAACAAGAC(C-G)ATGACAAGTCACTGGCCGGCTCAGACGTGT<br>-249 relative to initiation codon</td><td>Multiple sclerosis, susceptibility, association with</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=17010329&amp;dopt=Abstract' target=ref>Stoevring (2007) Clin Chim Acta <b>375,</b> 57</a></td><td style='white-space:nowrap;'><span class='fp' title='Disease-associated polymorphism'>DP</span>  <span class='gen' title='Chr11:111782697'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs14133' target='dbSNP' title='Link to rs14133'><span class='dbs'>dbSNP</span></a> <span class='dbs' title='MAF=0.263 MAF source=1000 Genomes'>FREQ</a></td></tr>

</table><a name='dels'></a><h3 class='heading'>Small deletions : 4 mutations <a href='#top'>[back to top]</a></h3><table class='gene'><tr><th>HGMD<br>accession</th>
<th>HGMD deletion</th><th><a href='http://www.hgvs.org/mutnomen/' target=HGVS>HGVS</a><br><span class='td'>(nucleotide)</span></th><th>Phenotype</th>
<th>Reference</th><th><a href='useful.php'>Extra<br>information</a></th></tr><tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD112644'><input type='submit' value='CD112644'></form></td><td>TTTCCAC^<sup><span class='td'><b>19</b></span></sup>TCCcCCAGCCGCCT</td><td>c.60delC</td><td>Muscular dystrophy, hypertonic fatal infantile</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21337604&amp;dopt=Abstract' target=ref>Del Bigio (2011) Ann Neurol <b>69,</b> 866</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111782389'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865141' target='dbSNP' title='Link to rs281865141'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD110061'><input type='submit' value='CD110061'></form></td><td>TGGTTTC^<sup><span class='td'><b>114</b></span></sup>ATCtCCAGGGAGTT</td><td>c.343delT</td><td>Myopathy, myofibrillar, infantile-onset</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=21130652&amp;dopt=Abstract' target=ref>Forrest (2011) Neuromuscul Disord <b>21,</b> 37</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779673'>GEN</span>   <a href='http://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?type=rs&rs=rs281865142' target='dbSNP' title='Link to rs281865142'><span class='dbs'>dbSNP</span></a> </td></tr>

<tr class='odd'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD013331'><input type='submit' value='CD013331'></form></td><td>GGACCA^<sup><span class='td'><b>149</b></span></sup>AGGAaACAGGTCTCT</td><td>c.450delA</td><td>Posterior polar cataract</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=11577372&amp;dopt=Abstract' target=ref>Berry (2001) Am J Hum Genet <b>69,</b> 1141</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779566'>GEN</span>  </td></tr>

<tr class='even'><td class='center'><form action='mut.php' method='POST'><input type='hidden' name='base' value='D'><input type='hidden' name='acc' value='CD033703'><input type='submit' value='CD033703'></form></td><td>GTCTCT^<sup><span class='td'><b>154</b></span></sup>GGCCctGAGCGCACCA</td><td>c.464_465delCT</td><td>Myopathy, myofibrillar</td><td><a href='http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?cmd=Retrieve&amp;db=PubMed&amp;list_uids=14681890&amp;dopt=Abstract' target=ref>Selcen (2003) Ann Neurol <b>54,</b> 804</a></td><td style='white-space:nowrap;'><span class='dm' title='Disease causing mutation'>DM</span>  <span class='gen' title='Chr11:111779551-111779552'>GEN</span>  </td></tr>

</table><hr><div class='bott2'>
Designed by P.D.Stenson HGMD&reg;<br><a class='black' href='copyright.php'>Copyright &copy; Cardiff University</a> 2013
</div>
<p class='spacer'></div></body></html>